version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app 
    restart: unless-stopped
    env_file: .env
    ports:
      - "9000:$SERVER_PORT"
#     depends_on:
#       - mongodb
#     environment:
#       MONGO_URL: mongodb://localhost:27017/FaciQuest

#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     restart: unless-stopped
#     env_file: .env
#     ports:
#       - 7000:27017  
#     volumes:
#       - dbdata:/data/db

# volumes:
#   dbdata: