version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app 
    restart: unless-stopped
    env_file: .env
    ports:
      - "9000:$SERVER_PORT"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$PASSWORD_USER"
      MONGO_INITDB_ROOT_PASSWORD: "$PASSWORD_DB"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: