name: faciquest
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dio: ^5.5.0+1
  go_router: ^14.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  collection: ^1.18.0
  awesome_extensions: ^2.0.16
  pinput: ^5.0.0
  # survey_kit: ^1.0.0-dev.5
  file_picker: ^8.0.0+1
  record: ^5.1.2
  just_audio: ^0.9.37
  input_quantity: ^2.4.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  uuid: ^4.5.1
  multi_dropdown: ^3.0.1
  pluto_grid: ^8.0.0
  skeletonizer: ^1.4.2
  lottie: ^3.1.2
  objectid: ^3.1.0
  # pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/lottie/
