name: faciquest
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dio: ^5.5.0+1
  go_router: ^16.2.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  collection: ^1.18.0
  awesome_extensions: ^2.0.16
  pinput: ^5.0.0
  # survey_kit: ^1.0.0-dev.5
  file_picker: ^10.3.2
  record: ^6.1.1
  just_audio: ^0.10.4
  input_quantity: ^2.5.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  uuid: ^4.5.1
  multi_dropdown: ^3.0.1

  skeletonizer: ^2.1.0+1
  lottie: ^3.1.2
  objectid: ^4.0.1
  trina_grid: ^2.0.0
  # pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/lottie/
