// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCva1aQ0Q-DzCpMZF0O41KqfThX2DprIrU',
    appId: '1:976687439846:web:f41b3ad0f92b5150844027',
    messagingSenderId: '976687439846',
    projectId: 'faciquest-b38af',
    authDomain: 'faciquest-b38af.firebaseapp.com',
    storageBucket: 'faciquest-b38af.firebasestorage.app',
    measurementId: 'G-WK2FBGH7ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl3o0wlI-xTq5P_451P9jWVCCFaBYNEbw',
    appId: '1:976687439846:android:9809d10ea3fd52e5844027',
    messagingSenderId: '976687439846',
    projectId: 'faciquest-b38af',
    storageBucket: 'faciquest-b38af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeew1qnePm9XOPQZGVDZ2TmAAzMn94Pa0',
    appId: '1:976687439846:ios:cb8f5493da34d207844027',
    messagingSenderId: '976687439846',
    projectId: 'faciquest-b38af',
    storageBucket: 'faciquest-b38af.firebasestorage.app',
    iosBundleId: 'com.example.faciquest',
  );
}
