// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'dart:convert';

import 'package:equatable/equatable.dart';

class Province extends Equatable {
  final String id;
  final String name;
  final String nameAr;
  final List<City> cities;
  const Province({
    this.id = '',
    this.name = '',
    this.nameAr = '',
    this.cities = const [],
  });

  Province copyWith({
    String? id,
    String? name,
    String? nameAr,
    List<City>? cities,
  }) {
    return Province(
      id: id ?? this.id,
      name: name ?? this.name,
      nameAr: nameAr ?? this.nameAr,
      cities: cities ?? this.cities,
    );
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'n': name,
      'ar': nameAr,
      'c': cities.map((x) => x.toMap()).toList(),
    };
  }

  factory Province.fromMap(Map<String, dynamic> map) {
    return Province(
      id: map['id'] as String,
      name: map['n'] as String,
      nameAr: map['ar'] as String,
      cities: List<City>.from(
        (map['c'] as List).map<City>(
          (x) => City.fromMap(x as Map<String, dynamic>),
        ),
      ),
    );
  }

  String toJson() => json.encode(toMap());

  factory Province.fromJson(String source) =>
      Province.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  bool get stringify => true;

  @override
  List<Object> get props => [id, name, nameAr, cities];
}

class City extends Equatable {
  final int id;
  final String name;
  final String nameAr;
  const City({
    this.id = 0,
    this.name = '',
    this.nameAr = '',
  });

  City copyWith({
    int? id,
    String? name,
    String? nameAr,
  }) {
    return City(
      id: id ?? this.id,
      name: name ?? this.name,
      nameAr: nameAr ?? this.nameAr,
    );
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'n': name,
      'ar': nameAr,
    };
  }

  factory City.fromMap(Map<String, dynamic> map) {
    return City(
      id: map['id'] as int,
      name: map['n'] as String,
      nameAr: map['ar'] as String,
    );
  }

  String toJson() => json.encode(toMap());

  factory City.fromJson(String source) =>
      City.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  bool get stringify => true;

  @override
  List<Object> get props => [id, name, nameAr];
}

class Data {
  final countries = {'Algeria'};
  List<Province> _provinces = [];

  List<Province> get provinces {
    if (_provinces.isNotEmpty) return _provinces;
    _provinces = algeriaCites.values.map((e) => Province.fromMap(e)).toList();
    return _provinces;
  }

  final algeriaCites = {
    "01": {
      "id": "01",
      "n": "Adrar",
      "ar": "أدرار",
      "c": [
        {"id": 22, "n": "Timekten", "ar": "تيمقتن"},
        {"id": 6, "n": "Bouda", "ar": "بودة"},
        {"id": 13, "n": "Ouled Ahmed Timmi", "ar": "أولاد أحمد تيمي"},
        {"id": 1, "n": "Adrar", "ar": "أدرار"},
        {"id": 9, "n": "Fenoughil", "ar": "فنوغيل"},
        {"id": 10, "n": "In Zghmir", "ar": "إن زغمير"},
        {"id": 16, "n": "Reggane", "ar": "رقان"},
        {"id": 17, "n": "Sali", "ar": "سالي"},
        {"id": 18, "n": "Sebaa", "ar": "السبع"},
        {"id": 27, "n": "Tsabit", "ar": "تسابيت"},
        {"id": 21, "n": "Tamest", "ar": "تامست"},
        {"id": 20, "n": "Tamantit", "ar": "تامنطيط"},
        {"id": 26, "n": "Tit", "ar": "تيت"},
        {"id": 28, "n": "Zaouiet Kounta", "ar": "زاوية كنتة"},
        {"id": 2, "n": "Akabli", "ar": "اقبلي"},
        {"id": 4, "n": "Aoulef", "ar": "أولف"}
      ]
    },
    "02": {
      "id": "02",
      "n": "Chlef",
      "ar": " الشلف",
      "c": [
        {"id": 60, "n": "Talassa", "ar": "تلعصة"},
        {"id": 63, "n": "Zeboudja", "ar": "الزبوجة"},
        {"id": 41, "n": "El Hadjadj", "ar": "الحجاج"},
        {"id": 52, "n": "Ouled Ben Abdelkader", "ar": "أولاد بن عبد القادر"},
        {"id": 30, "n": "Ain Merane", "ar": "عين مران"},
        {"id": 37, "n": "Breira", "ar": "بريرة"},
        {"id": 51, "n": "Ouled Abbes", "ar": "أولاد عباس"},
        {"id": 48, "n": "Oued Fodda", "ar": "وادي الفضة"},
        {"id": 34, "n": "Beni Rached", "ar": "بني راشد"},
        {"id": 45, "n": "Herenfa", "ar": "الهرانفة"},
        {"id": 59, "n": "Tadjena", "ar": "تاجنة"},
        {"id": 43, "n": "El Marsa", "ar": "المرسى"},
        {"id": 39, "n": "Chlef", "ar": "الشلف"},
        {"id": 54, "n": "Oum Drou", "ar": "أم الدروع"},
        {"id": 55, "n": "Sendjas", "ar": "سنجاس"},
        {"id": 56, "n": "Sidi Abderrahmane", "ar": "سيدي عبد الرحمن"},
        {"id": 57, "n": "Sidi Akkacha", "ar": "سيدي عكاشة"},
        {"id": 62, "n": "Tenes", "ar": "تنس"},
        {"id": 32, "n": "Beni  Bouattab", "ar": "بني بوعتاب"},
        {"id": 42, "n": "El Karimia", "ar": "الكريمية"},
        {"id": 44, "n": "Harchoun", "ar": "حرشون"},
        {"id": 36, "n": "Bouzeghaia", "ar": "بوزغاية"},
        {"id": 61, "n": "Taougrit", "ar": "تاوقريت"},
        {"id": 33, "n": "Beni Haoua", "ar": "بني حواء"},
        {"id": 29, "n": "Abou El Hassane", "ar": "أبو الحسن"},
        {"id": 49, "n": "Oued Goussine", "ar": "وادي قوسين"},
        {"id": 38, "n": "Chettia", "ar": "الشطية"},
        {"id": 47, "n": "Moussadek", "ar": "مصدق"},
        {"id": 53, "n": "Ouled Fares", "ar": "أولاد فارس"},
        {"id": 35, "n": "Boukadir", "ar": "بوقادير"},
        {"id": 50, "n": "Oued Sly", "ar": "وادي سلي"},
        {"id": 58, "n": "Sobha", "ar": "الصبحة"},
        {"id": 31, "n": "Benairia", "ar": "بنايرية"},
        {"id": 46, "n": "Labiod Medjadja", "ar": "الأبيض مجاجة"},
        {"id": 40, "n": "Dahra", "ar": "الظهرة"}
      ]
    },
    "03": {
      "id": "03",
      "n": "Laghouat",
      "ar": "الأغواط",
      "c": [
        {"id": 67, "n": "El Beidha", "ar": "البيضاء"},
        {"id": 73, "n": "Gueltat Sidi Saad", "ar": "قلتة سيدي سعد"},
        {"id": 69, "n": "Brida", "ar": "بريدة"},
        {"id": 66, "n": "Ain Sidi Ali", "ar": "عين سيدي علي"},
        {"id": 85, "n": "Tadjemout", "ar": "تاجموت"},
        {"id": 74, "n": "Hadj Mechri", "ar": "الحاج مشري"},
        {"id": 87, "n": "Taouiala", "ar": "تاويالة"},
        {"id": 71, "n": "El Ghicha", "ar": "الغيشة"},
        {"id": 86, "n": "Tadjrouna", "ar": "تاجرونة"},
        {"id": 82, "n": "Sebgag", "ar": "سبقاق"},
        {"id": 83, "n": "Sidi Bouzid", "ar": "سيدي بوزيد"},
        {"id": 80, "n": "Oued Morra", "ar": "وادي مرة"},
        {"id": 79, "n": "Laghouat", "ar": "الأغواط"},
        {"id": 81, "n": "Oued M'zi", "ar": "وادي مزي"},
        {"id": 78, "n": "Ksar El Hirane", "ar": "قصر الحيران"},
        {"id": 70, "n": "El Assafia", "ar": "العسافية"},
        {"id": 84, "n": "Sidi Makhlouf", "ar": "سيدي مخلوف"},
        {"id": 75, "n": "Hassi Delaa", "ar": "حاسي الدلاعة"},
        {"id": 76, "n": "Hassi R'mel", "ar": "حاسي الرمل"},
        {"id": 65, "n": "Ain Madhi", "ar": "عين ماضي"},
        {"id": 72, "n": "El Haouaita", "ar": "الحويطة"},
        {"id": 77, "n": "Kheneg", "ar": "الخنق"},
        {"id": 68, "n": "Benacer Benchohra", "ar": "بن ناصر بن شهرة"},
        {"id": 64, "n": "Aflou", "ar": "أفلو"}
      ]
    },
    "04": {
      "id": "04",
      "n": "Oum El Bouaghi",
      "ar": "أم البواقي",
      "c": [
        {"id": 104, "n": "Fkirina", "ar": "فكيرينة"},
        {
          "id": 102,
          "n": "El Fedjoudj Boughrara Sa",
          "ar": "الفجوج بوغرارة سعودي"
        },
        {"id": 91, "n": "Ain Fekroun", "ar": "عين فكرون"},
        {"id": 113, "n": "Rahia", "ar": "الرحية"},
        {"id": 107, "n": "Meskiana", "ar": "مسكيانة"},
        {"id": 100, "n": "El Belala", "ar": "البلالة"},
        {"id": 95, "n": "Behir Chergui", "ar": "بحير الشرقي"},
        {"id": 106, "n": "Ksar Sbahi", "ar": "قصر الصباحي"},
        {"id": 115, "n": "Souk Naamane", "ar": "سوق نعمان"},
        {"id": 111, "n": "Ouled Zouai", "ar": "أولاد زواي"},
        {"id": 112, "n": "Oum El Bouaghi", "ar": "أم البواقي"},
        {"id": 88, "n": "Ain Babouche", "ar": "عين ببوش"},
        {"id": 94, "n": "Ain Zitoun", "ar": "عين الزيتون"},
        {"id": 97, "n": "Bir Chouhada", "ar": "بئر الشهداء"},
        {"id": 89, "n": "Ain Beida", "ar": "عين البيضاء"},
        {"id": 96, "n": "Berriche", "ar": "بريش"},
        {"id": 116, "n": "Zorg", "ar": "الزرق"},
        {"id": 93, "n": "Ain M'lila", "ar": "عين مليلة"},
        {"id": 109, "n": "Ouled Gacem", "ar": "أولاد قاسم"},
        {"id": 110, "n": "Ouled Hamla", "ar": "أولاد حملة"},
        {"id": 99, "n": "El Amiria", "ar": "العامرية"},
        {"id": 114, "n": "Sigus", "ar": "سيقوس"},
        {"id": 108, "n": "Oued Nini", "ar": "وادي نيني"},
        {"id": 90, "n": "Ain Diss", "ar": "عين الديس"},
        {"id": 98, "n": "Dhalaa", "ar": "الضلعة"},
        {"id": 101, "n": "El Djazia", "ar": "الجازية"},
        {"id": 92, "n": "Ain Kercha", "ar": "عين كرشة"},
        {"id": 103, "n": "El Harmilia", "ar": "الحرملية"},
        {"id": 105, "n": "Hanchir Toumghani", "ar": "هنشير تومغني"}
      ]
    },
    "05": {
      "id": "05",
      "n": "Batna",
      "ar": "باتنة",
      "c": [
        {"id": 150, "n": "Maafa", "ar": "معافة"},
        {"id": 139, "n": "Gosbat", "ar": "القصبات"},
        {"id": 176, "n": "Timgad", "ar": "تيمقاد"},
        {"id": 170, "n": "Taxlent", "ar": "تاكسلانت"},
        {"id": 161, "n": "Ouled Si Slimane", "ar": "أولاد سي سليمان"},
        {"id": 148, "n": "Lemcene", "ar": "لمسان"},
        {"id": 169, "n": "Talkhamt", "ar": "تالخمت"},
        {"id": 164, "n": "Ras El Aioun", "ar": "رأس العيون"},
        {"id": 163, "n": "Rahbat", "ar": "الرحبات"},
        {"id": 160, "n": "Ouled Sellem", "ar": "أولاد سلام"},
        {"id": 140, "n": "Guigba", "ar": "القيقبة"},
        {"id": 172, "n": "Teniet El Abed", "ar": "ثنية العابد"},
        {"id": 123, "n": "Batna", "ar": "باتنة"},
        {"id": 136, "n": "Fesdis", "ar": "فسديس"},
        {"id": 154, "n": "Oued Chaaba", "ar": "وادي الشعبة"},
        {"id": 141, "n": "Hidoussa", "ar": "حيدوسة"},
        {"id": 145, "n": "Ksar Bellezma", "ar": "قصر بلزمة"},
        {"id": 152, "n": "Merouana", "ar": "مروانة"},
        {"id": 155, "n": "Oued El Ma", "ar": "وادي الماء"},
        {"id": 147, "n": "Lazrou", "ar": "لازرو"},
        {"id": 167, "n": "Seriana", "ar": "سريانة"},
        {"id": 177, "n": "Zanet El Beida", "ar": "زانة البيضاء"},
        {"id": 151, "n": "Menaa", "ar": "منعة"},
        {"id": 174, "n": "Tigharghar", "ar": "تغرغار"},
        {"id": 119, "n": "Ain Yagout", "ar": "عين ياقوت"},
        {"id": 128, "n": "Boumia", "ar": "بومية"},
        {"id": 132, "n": "Djerma", "ar": "جرمة"},
        {"id": 135, "n": "El Madher", "ar": "المعذر"},
        {"id": 162, "n": "Ouyoun El Assafir", "ar": "عيون العصافير"},
        {"id": 171, "n": "Tazoult", "ar": "تازولت"},
        {"id": 127, "n": "Boumagueur", "ar": "بومقر"},
        {"id": 153, "n": "N Gaous", "ar": "نقاوس"},
        {"id": 165, "n": "Sefiane", "ar": "سفيان"},
        {"id": 120, "n": "Arris", "ar": "أريس"},
        {"id": 173, "n": "Tighanimine", "ar": "تيغانمين"},
        {"id": 117, "n": "Ain Djasser", "ar": "عين جاسر"},
        {"id": 134, "n": "El Hassi", "ar": "الحاسي"},
        {"id": 166, "n": "Seggana", "ar": "سقانة"},
        {"id": 175, "n": "Tilatou", "ar": "تيلاطو"},
        {"id": 137, "n": "Foum Toub", "ar": "فم الطوب"},
        {"id": 142, "n": "Ichemoul", "ar": "إشمول"},
        {"id": 143, "n": "Inoughissen", "ar": "إينوغيسن"},
        {"id": 129, "n": "Bouzina", "ar": "بوزينة"},
        {"id": 146, "n": "Larbaa", "ar": "لارباع"},
        {"id": 126, "n": "Boulhilat", "ar": "بولهيلات"},
        {"id": 130, "n": "Chemora", "ar": "الشمرة"},
        {"id": 122, "n": "Barika", "ar": "بريكة"},
        {"id": 125, "n": "Bitam", "ar": "بيطام"},
        {"id": 149, "n": "M Doukal", "ar": "إمدوكل"},
        {"id": 121, "n": "Azil Abedelkader", "ar": "عزيل عبد القادر"},
        {"id": 133, "n": "Djezzar", "ar": "الجزار"},
        {"id": 157, "n": "Ouled Ammar", "ar": "أولاد عمار"},
        {"id": 138, "n": "Ghassira", "ar": "غسيرة"},
        {"id": 144, "n": "Kimmel", "ar": "كيمل"},
        {"id": 168, "n": "T Kout", "ar": "تكوت"},
        {"id": 118, "n": "Ain Touta", "ar": "عين التوتة"},
        {
          "id": 124,
          "n": "Beni Foudhala El Hakania",
          "ar": "بني فضالة الحقانية"
        },
        {"id": 159, "n": "Ouled Fadel", "ar": "أولاد فاضل"},
        {"id": 158, "n": "Ouled Aouf", "ar": "أولاد عوف"},
        {"id": 131, "n": "Chir", "ar": "شير"},
        {"id": 156, "n": "Oued Taga", "ar": "وادي الطاقة"}
      ]
    },
    "06": {
      "id": "06",
      "n": "Béjaïa",
      "ar": " بجاية",
      "c": [
        {"id": 212, "n": "Sidi Ayad", "ar": "سيدي عياد"},
        {"id": 186, "n": "Barbacha", "ar": "برباشة"},
        {"id": 199, "n": "Leflaye", "ar": "الفلاي"},
        {"id": 206, "n": "Kendira", "ar": "كنديرة"},
        {"id": 213, "n": "Sidi-Aich", "ar": "سيدي عيش"},
        {"id": 225, "n": "Tifra", "ar": "تيفرة"},
        {"id": 227, "n": "Tinebdar", "ar": "تينبدار"},
        {"id": 200, "n": "El Kseur", "ar": "القصر"},
        {"id": 201, "n": "Fenaia Il Maten", "ar": "فناية الماثن"},
        {"id": 229, "n": "Toudja", "ar": "توجة"},
        {"id": 198, "n": "Dra El Caid", "ar": "ذراع القايد"},
        {"id": 207, "n": "Kherrata", "ar": "خراطة"},
        {"id": 187, "n": "Bejaia", "ar": "بجاية"},
        {"id": 210, "n": "Oued Ghir", "ar": "وادي غير"},
        {"id": 191, "n": "Benimaouche", "ar": "بني معوش"},
        {"id": 188, "n": "Beni Djellil", "ar": "بني جليل"},
        {"id": 202, "n": "Feraoun", "ar": "فرعون"},
        {"id": 214, "n": "Smaoun", "ar": "سمعون"},
        {"id": 226, "n": "Timezrit", "ar": "تيمزريت"},
        {"id": 209, "n": "Melbou", "ar": "مالبو"},
        {"id": 215, "n": "Souk El Tenine", "ar": "سوق لإثنين"},
        {"id": 219, "n": "Tamridjet", "ar": "تامريجت"},
        {"id": 194, "n": "Boukhelifa", "ar": "بوخليفة"},
        {"id": 217, "n": "Tala Hamza", "ar": "تالة حمزة"},
        {"id": 224, "n": "Tichy", "ar": "تيشي"},
        {"id": 179, "n": "Ait R'zine", "ar": "أيت رزين"},
        {"id": 204, "n": "Ighil-Ali", "ar": "إغيل علي"},
        {"id": 180, "n": "Ait-Smail", "ar": "أيت إسماعيل"},
        {"id": 197, "n": "Darguina", "ar": "درقينة"},
        {"id": 221, "n": "Taskriout", "ar": "تاسكريوت"},
        {"id": 185, "n": "Aokas", "ar": "أوقاس"},
        {"id": 228, "n": "Tizi-N'berber", "ar": "تيزي نبربر"},
        {"id": 178, "n": "Adekar", "ar": "أدكار"},
        {"id": 189, "n": "Beni K'sila", "ar": "بني كسيلة"},
        {"id": 220, "n": "Taourit Ighil", "ar": "تاوريرت إغيل"},
        {"id": 181, "n": "Akbou", "ar": "أقبو"},
        {"id": 195, "n": "Chellata", "ar": "شلاطة"},
        {"id": 205, "n": "Ighram", "ar": "اغرم"},
        {"id": 218, "n": "Tamokra", "ar": "تامقرة"},
        {"id": 183, "n": "Amalou", "ar": "أمالو"},
        {"id": 193, "n": "Bouhamza", "ar": "بوحمزة"},
        {"id": 208, "n": "M'cisna", "ar": "مسيسنة"},
        {"id": 211, "n": "Seddouk", "ar": "صدوق"},
        {"id": 190, "n": "Beni-Mallikeche", "ar": "بني مليكش"},
        {"id": 192, "n": "Boudjellil", "ar": "بو جليل"},
        {"id": 222, "n": "Tazmalt", "ar": "تازمالت"},
        {"id": 182, "n": "Akfadou", "ar": "أكفادو"},
        {"id": 196, "n": "Chemini", "ar": "شميني"},
        {"id": 216, "n": "Souk Oufella", "ar": "سوق اوفلا"},
        {"id": 223, "n": "Tibane", "ar": "طيبان"},
        {"id": 203, "n": "Ouzellaguen", "ar": "أوزلاقن"},
        {"id": 184, "n": "Amizour", "ar": "أميزور"}
      ]
    },
    "07": {
      "id": "07",
      "n": "Biskra",
      "ar": "بسكرة",
      "c": [
        {"id": 241, "n": "El Feidh", "ar": "الفيض"},
        {"id": 249, "n": "Lichana", "ar": "ليشانة"},
        {"id": 235, "n": "Bouchakroun", "ar": "بوشقرون"},
        {"id": 252, "n": "Mekhadma", "ar": "مخادمة"},
        {"id": 239, "n": "Djemorah", "ar": "جمورة"},
        {"id": 236, "n": "Branis", "ar": "برانيس"},
        {"id": 246, "n": "El Outaya", "ar": "الوطاية"},
        {"id": 245, "n": "El Kantara", "ar": "القنطرة"},
        {"id": 248, "n": "Khenguet Sidi Nadji", "ar": "خنقة سيدي ناجي"},
        {"id": 231, "n": "Ain Zaatout", "ar": "عين زعطوط"},
        {"id": 262, "n": "Zeribet El Oued", "ar": "زريبة الوادي"},
        {"id": 253, "n": "Meziraa", "ar": "المزيرعة"},
        {"id": 233, "n": "Biskra", "ar": "بسكرة"},
        {"id": 243, "n": "El Hadjab", "ar": "الحاجب"},
        {"id": 254, "n": "M'lili", "ar": "مليلي"},
        {"id": 247, "n": "Foughala", "ar": "فوغالة"},
        {"id": 242, "n": "El Ghrous", "ar": "الغروس"},
        {"id": 234, "n": "Bordj Ben Azzouz", "ar": "برج بن عزوز"},
        {"id": 257, "n": "Ourlal", "ar": "أورلال"},
        {"id": 256, "n": "Oumache", "ar": "أوماش"},
        {"id": 230, "n": "Ain Naga", "ar": "عين الناقة"},
        {"id": 238, "n": "Chetma", "ar": "شتمة"},
        {"id": 244, "n": "El Haouch", "ar": "الحوش"},
        {"id": 260, "n": "Sidi Okba", "ar": "سيدي عقبة"},
        {"id": 251, "n": "M'chouneche", "ar": "مشونش"},
        {"id": 250, "n": "Lioua", "ar": "ليوة"},
        {"id": 261, "n": "Tolga", "ar": "طولقة"}
      ]
    },
    "08": {
      "id": "08",
      "n": "Béchar",
      "ar": "بشار",
      "c": [
        {"id": 264, "n": "Bechar", "ar": "بشار"},
        {"id": 268, "n": "Boukais", "ar": "بوكايس"},
        {"id": 275, "n": "Lahmar", "ar": "لحمر"},
        {"id": 278, "n": "Mogheul", "ar": "موغل"},
        {"id": 277, "n": "Meridja", "ar": "المريجة"},
        {"id": 281, "n": "Taghit", "ar": "تاغيت"},
        {"id": 263, "n": "Abadla", "ar": "العبادلة"},
        {"id": 270, "n": "Erg-Ferradj", "ar": "عرق فراج"},
        {
          "id": 276,
          "n": "Machraa-Houari-Boumediene",
          "ar": "مشرع هواري بومدين"
        },
        {"id": 267, "n": "Beni-Ounif", "ar": "بني ونيف"},
        {"id": 280, "n": "Tabelbala", "ar": "تبلبالة"},
        {"id": 272, "n": "Kenadsa", "ar": "القنادسة"}
      ]
    },
    "09": {
      "id": "09",
      "n": "Blida",
      "ar": "البليدة",
      "c": [
        {"id": 285, "n": "Beni Mered", "ar": "بني مراد"},
        {"id": 305, "n": "Ouled Slama", "ar": "اولاد سلامة"},
        {"id": 302, "n": "Mouzaia", "ar": "موزاية"},
        {"id": 299, "n": "Hammam Elouane", "ar": "حمام ملوان"},
        {"id": 291, "n": "Bougara", "ar": "بوقرة"},
        {"id": 307, "n": "Souhane", "ar": "صوحان"},
        {"id": 300, "n": "Larbaa", "ar": "الأربعاء"},
        {"id": 308, "n": "Soumaa", "ar": "الصومعة"},
        {"id": 298, "n": "Guerrouaou", "ar": "قرواو"},
        {"id": 290, "n": "Boufarik", "ar": "بوفاريك"},
        {"id": 301, "n": "Meftah", "ar": "مفتاح"},
        {"id": 294, "n": "Chiffa", "ar": "الشفة"},
        {"id": 284, "n": "Ain Romana", "ar": "عين الرمانة"},
        {"id": 303, "n": "Oued  Djer", "ar": "وادي جر"},
        {"id": 297, "n": "El-Affroun", "ar": "العفرون"},
        {"id": 306, "n": "Ouled Yaich", "ar": "أولاد يعيش"},
        {"id": 295, "n": "Chrea", "ar": "الشريعة"},
        {"id": 296, "n": "Djebabra", "ar": "جبابرة"},
        {"id": 304, "n": "Oued El Alleug", "ar": "وادي العلايق"},
        {"id": 287, "n": "Benkhelil", "ar": "بن خليل"},
        {"id": 286, "n": "Beni-Tamou", "ar": "بني تامو"},
        {"id": 293, "n": "Chebli", "ar": "الشبلي"},
        {"id": 292, "n": "Bouinan", "ar": "بوعينان"},
        {"id": 289, "n": "Bouarfa", "ar": "بوعرفة"},
        {"id": 288, "n": "Blida", "ar": "البليدة"}
      ]
    },
    "10": {
      "id": "10",
      "n": "Bouira",
      "ar": "البويرة",
      "c": [
        {"id": 312, "n": "Ain Laloui", "ar": "عين العلوي"},
        {"id": 334, "n": "Hadjera Zerga", "ar": "الحجرة الزرقاء"},
        {"id": 342, "n": "Mezdour", "ar": "مزدور"},
        {"id": 351, "n": "Taguedite", "ar": "تاقديت"},
        {"id": 346, "n": "Ridane", "ar": "ريدان"},
        {"id": 341, "n": "Maamora", "ar": "المعمورة"},
        {"id": 331, "n": "El-Hakimia", "ar": "الحاكمية"},
        {"id": 310, "n": "Ahl El Ksar", "ar": "أهل القصر"},
        {"id": 325, "n": "Dirah", "ar": "ديرة"},
        {"id": 324, "n": "Dechmia", "ar": "الدشمية"},
        {"id": 317, "n": "Bechloul", "ar": "بشلول"},
        {"id": 352, "n": "Ath Mansour", "ar": "آث  منصور"},
        {"id": 347, "n": "Saharidj", "ar": "سحاريج"},
        {"id": 327, "n": "El Adjiba", "ar": "العجيبة"},
        {"id": 328, "n": "El Asnam", "ar": "الأسنام"},
        {"id": 339, "n": "M Chedallah", "ar": "أمشدالة"},
        {"id": 319, "n": "Bordj Okhriss", "ar": "برج أوخريص"},
        {"id": 349, "n": "Sour El Ghozlane", "ar": "سور الغزلان"},
        {"id": 336, "n": "Hanif", "ar": "حنيف"},
        {"id": 323, "n": "Chorfa", "ar": "شرفة"},
        {"id": 344, "n": "Ouled Rached", "ar": "أولاد راشد"},
        {"id": 311, "n": "Ain El Hadjar", "ar": "عين الحجر"},
        {"id": 309, "n": "Aghbalou", "ar": "أغبالو"},
        {"id": 345, "n": "Raouraoua", "ar": "روراوة"},
        {"id": 330, "n": "El Khabouzia", "ar": "الخبوزية"},
        {"id": 318, "n": "Bir Ghbalou", "ar": "بئر غبالو"},
        {"id": 321, "n": "Bouira", "ar": "البويرة"},
        {"id": 313, "n": "Ain Turk", "ar": "عين الترك"},
        {"id": 315, "n": "Ait Laaziz", "ar": "أيت لعزيز"},
        {"id": 314, "n": "Ain-Bessem", "ar": "عين بسام"},
        {"id": 332, "n": "El-Mokrani", "ar": "المقراني"},
        {"id": 348, "n": "Souk El Khemis", "ar": "سوق الخميس"},
        {"id": 316, "n": "Aomar", "ar": "أعمر"},
        {"id": 326, "n": "Djebahia", "ar": "جباحية"},
        {"id": 329, "n": "El Hachimia", "ar": "الهاشمية"},
        {"id": 335, "n": "Haizer", "ar": "حيزر"},
        {"id": 350, "n": "Taghzout", "ar": "تاغزوت"},
        {"id": 320, "n": "Bouderbala", "ar": "بودربالة"},
        {"id": 322, "n": "Boukram", "ar": "بوكرم"},
        {"id": 333, "n": "Guerrouma", "ar": "قرومة"},
        {"id": 338, "n": "Lakhdaria", "ar": "الأخضرية"},
        {"id": 340, "n": "Maala", "ar": "معلة"},
        {"id": 337, "n": "Kadiria", "ar": "قادرية"},
        {"id": 353, "n": "Z'barbar (El Isseri )", "ar": "زبربر"},
        {"id": 343, "n": "Oued El Berdi", "ar": "وادي البردي"}
      ]
    },
    "11": {
      "id": "11",
      "n": "Tamanrasset",
      "ar": "تمنراست",
      "c": [
        {"id": 362, "n": "Tazrouk", "ar": "تاظروك"},
        {"id": 354, "n": "Abelsa", "ar": "ابلسة"},
        {"id": 361, "n": "Tamanrasset", "ar": "تمنراست"},
        {"id": 355, "n": "Ain Amguel", "ar": "عين امقل"},
        {"id": 359, "n": "Idles", "ar": "أدلس"}
      ]
    },
    "12": {
      "id": "12",
      "n": "Tébessa",
      "ar": "تبسة",
      "c": [
        {"id": 380, "n": "El-Houidjbet", "ar": "الحويجبات"},
        {"id": 379, "n": "El-Aouinet", "ar": "العوينات"},
        {"id": 381, "n": "Ferkane", "ar": "فركان"},
        {"id": 385, "n": "Negrine", "ar": "نقرين"},
        {"id": 368, "n": "Bir Mokkadem", "ar": "بئر مقدم"},
        {"id": 367, "n": "Bir Dheheb", "ar": "بئر الذهب"},
        {"id": 388, "n": "Saf Saf El Ouesra", "ar": "صفصاف الوسرى"},
        {"id": 382, "n": "Guorriguer", "ar": "قريقر"},
        {"id": 366, "n": "Bekkaria", "ar": "بكارية"},
        {"id": 371, "n": "Boulhaf Dyr", "ar": "بولحاف الدير"},
        {"id": 387, "n": "Oum Ali", "ar": "أم علي"},
        {"id": 370, "n": "Boukhadra", "ar": "بوخضرة"},
        {"id": 374, "n": "El Malabiod", "ar": "الماء الابيض"},
        {"id": 386, "n": "Ouenza", "ar": "الونزة"},
        {"id": 375, "n": "El Meridj", "ar": "المريج"},
        {"id": 364, "n": "Ain Zerga", "ar": "عين الزرقاء"},
        {"id": 389, "n": "Stah Guentis", "ar": "سطح قنطيس"},
        {"id": 377, "n": "El Ogla", "ar": "العقلة"},
        {"id": 376, "n": "El Mezeraa", "ar": "المزرعة"},
        {"id": 365, "n": "Bedjene", "ar": "بجن"},
        {"id": 384, "n": "Morsott", "ar": "مرسط"},
        {"id": 391, "n": "Telidjen", "ar": "ثليجان"},
        {"id": 372, "n": "Cheria", "ar": "الشريعة"},
        {"id": 378, "n": "El Ogla El Malha", "ar": "العقلة المالحة"},
        {"id": 369, "n": "Bir-El-Ater", "ar": "بئر العاتر"},
        {"id": 390, "n": "Tebessa", "ar": "تبسة"},
        {"id": 383, "n": "Hammamet", "ar": "الحمامات"},
        {"id": 373, "n": "El Kouif", "ar": "الكويف"}
      ]
    },
    "13": {
      "id": "13",
      "n": "Tlemcen",
      "ar": "تلمسان",
      "c": [
        {"id": 400, "n": "Bab El Assa", "ar": "باب العسة"},
        {"id": 441, "n": "Terny Beni Hediel", "ar": "تيرني بني هديل"},
        {"id": 424, "n": "Mansourah", "ar": "منصورة"},
        {"id": 404, "n": "Beni Mester", "ar": "بني مستر"},
        {"id": 394, "n": "Ain Ghoraba", "ar": "عين غرابة"},
        {"id": 411, "n": "Chetouane", "ar": "شتوان"},
        {"id": 399, "n": "Amieur", "ar": "عمير"},
        {"id": 393, "n": "Ain Fezza", "ar": "عين فزة"},
        {"id": 422, "n": "Honnaine", "ar": "هنين"},
        {"id": 403, "n": "Beni Khellad", "ar": "بني خلاد"},
        {"id": 436, "n": "Sidi Djillali", "ar": "سيدي الجيلالي"},
        {"id": 410, "n": "Bouihi", "ar": "البويهي"},
        {"id": 427, "n": "Nedroma", "ar": "ندرومة"},
        {"id": 426, "n": "M'sirda Fouaga", "ar": "مسيردة الفواقة"},
        {"id": 425, "n": "Marsa Ben M'hidi", "ar": "مرسى بن مهيدي"},
        {"id": 437, "n": "Sidi Medjahed", "ar": "سيدي مجاهد"},
        {"id": 402, "n": "Beni Boussaid", "ar": "بني بوسعيد"},
        {"id": 434, "n": "Sebdou", "ar": "سبدو"},
        {"id": 417, "n": "El Gor", "ar": "القور"},
        {"id": 414, "n": "El Aricha", "ar": "العريشة"},
        {"id": 409, "n": "Bouhlou", "ar": "بوحلو"},
        {"id": 423, "n": "Maghnia", "ar": "مغنية"},
        {"id": 420, "n": "Hammam Boughrara", "ar": "حمام بوغرارة"},
        {"id": 444, "n": "Zenata", "ar": "زناتة"},
        {"id": 430, "n": "Ouled Riyah", "ar": "أولاد رياح"},
        {"id": 421, "n": "Hennaya", "ar": "الحناية"},
        {"id": 435, "n": "Sidi Abdelli", "ar": "سيدي العبدلي"},
        {"id": 440, "n": "Souk Tleta", "ar": "سوق الثلاثاء"},
        {"id": 408, "n": "Bensekrane", "ar": "بن سكران"},
        {"id": 418, "n": "Fellaoucene", "ar": "فلاوسن"},
        {"id": 395, "n": "Ain Kebira", "ar": "عين الكبيرة"},
        {"id": 392, "n": "Ain Fetah", "ar": "عين فتاح"},
        {"id": 443, "n": "Tlemcen", "ar": "تلمسان"},
        {"id": 396, "n": "Ain Nehala", "ar": "عين النحالة"},
        {"id": 397, "n": "Ain Tellout", "ar": "عين تالوت"},
        {"id": 398, "n": "Ain Youcef", "ar": "عين يوسف"},
        {"id": 405, "n": "Beni Ouarsous", "ar": "بني وارسوس"},
        {"id": 416, "n": "El Fehoul", "ar": "الفحول"},
        {"id": 431, "n": "Remchi", "ar": "الرمشي"},
        {"id": 433, "n": "Sebbaa Chioukh", "ar": "سبعة شيوخ"},
        {"id": 439, "n": "Souani", "ar": "السواني"},
        {"id": 432, "n": "Sabra", "ar": "صبرة"},
        {"id": 412, "n": "Dar Yaghmoracen", "ar": "دار يغمراسن"},
        {"id": 419, "n": "Ghazaouet", "ar": "الغزوات"},
        {"id": 438, "n": "Souahlia", "ar": "السواحلية"},
        {"id": 442, "n": "Tianet", "ar": "تيانت"},
        {"id": 406, "n": "Beni Smiel", "ar": "بني صميل"},
        {"id": 428, "n": "Oued Lakhdar", "ar": "وادي الخضر"},
        {"id": 429, "n": "Ouled Mimoun", "ar": "أولاد ميمون"},
        {"id": 401, "n": "Beni Bahdel", "ar": "بني بهدل"},
        {"id": 407, "n": "Beni Snous", "ar": "بني سنوس"},
        {"id": 415, "n": "Azail", "ar": "العزايل"},
        {"id": 413, "n": "Djebala", "ar": "جبالة"}
      ]
    },
    "14": {
      "id": "14",
      "n": "Tiaret",
      "ar": "تيارت",
      "c": [
        {"id": 461, "n": "Mahdia", "ar": "مهدية"},
        {"id": 447, "n": "Ain Dzarit", "ar": "عين دزاريت"},
        {"id": 472, "n": "Sebaine", "ar": "السبعين"},
        {"id": 455, "n": "Faidja", "ar": "الفايجة"},
        {"id": 475, "n": "Si Abdelghani", "ar": "سي عبد الغني"},
        {"id": 480, "n": "Sougueur", "ar": "السوقر"},
        {"id": 485, "n": "Tousnina", "ar": "توسنينة"},
        {"id": 465, "n": "Meghila", "ar": "مغيلة"},
        {"id": 473, "n": "Sebt", "ar": "السبت"},
        {"id": 479, "n": "Sidi Hosni", "ar": "سيدي حسني"},
        {"id": 448, "n": "Ain El Hadid", "ar": "عين الحديد"},
        {"id": 456, "n": "Frenda", "ar": "فرندة"},
        {"id": 482, "n": "Takhemaret", "ar": "تخمرت"},
        {"id": 449, "n": "Ain Kermes", "ar": "عين كرمس"},
        {"id": 453, "n": "Djebilet Rosfa", "ar": "جبيلات الرصفاء"},
        {"id": 460, "n": "Madna", "ar": "مادنة"},
        {"id": 463, "n": "Medrissa", "ar": "مدريسة"},
        {"id": 476, "n": "Sidi Abderrahmane", "ar": "سيدي عبد الرحمن"},
        {"id": 459, "n": "Ksar Chellala", "ar": "قصر الشلالة"},
        {"id": 457, "n": "Guertoufa", "ar": "قرطوفة"},
        {"id": 474, "n": "Serghine", "ar": "سرغين"},
        {
          "id": 486,
          "n": "Zmalet El Emir Abdelkade",
          "ar": "زمالة  الأمير عبد القادر"
        },
        {"id": 469, "n": "Oued Lilli", "ar": "وادي ليلي"},
        {"id": 477, "n": "Sidi Ali Mellal", "ar": "سيدي علي ملال"},
        {"id": 454, "n": "Djillali Ben Amar", "ar": "جيلالي بن عمار"},
        {"id": 462, "n": "Mechraa Safa", "ar": "مشرع الصفا"},
        {"id": 481, "n": "Tagdempt", "ar": "تاقدمت"},
        {"id": 450, "n": "Bougara", "ar": "بوقرة"},
        {"id": 458, "n": "Hamadia", "ar": "حمادية"},
        {"id": 471, "n": "Rechaiga", "ar": "الرشايقة"},
        {"id": 484, "n": "Tidda", "ar": "تيدة"},
        {"id": 467, "n": "Nadorah", "ar": "الناظورة"},
        {"id": 483, "n": "Tiaret", "ar": "تيارت"},
        {"id": 464, "n": "Medroussa", "ar": "مدروسة"},
        {"id": 466, "n": "Mellakou", "ar": "ملاكو"},
        {"id": 478, "n": "Sidi Bakhti", "ar": "سيدي بختي"},
        {"id": 446, "n": "Ain Deheb", "ar": "عين الذهب"},
        {"id": 451, "n": "Chehaima", "ar": "شحيمة"},
        {"id": 468, "n": "Naima", "ar": "النعيمة"},
        {"id": 445, "n": "Ain Bouchekif", "ar": "عين بوشقيف"},
        {"id": 452, "n": "Dahmouni", "ar": "دحموني"},
        {"id": 470, "n": "Rahouia", "ar": "الرحوية"}
      ]
    },
    "15": {
      "id": "15",
      "n": "Tizi Ouzou",
      "ar": "تيزي وزو",
      "c": [
        {"id": 535, "n": "Mizrana", "ar": "ميزرانـــة"},
        {"id": 522, "n": "Idjeur", "ar": "إيجــار"},
        {"id": 510, "n": "Beni-Douala", "ar": "بني دوالة"},
        {"id": 512, "n": "Beni-Zikki", "ar": "بني زيكــي"},
        {"id": 527, "n": "Illoula Oumalou", "ar": "إيلولة أومـــالو"},
        {"id": 489, "n": "Agouni-Gueghrane", "ar": "أقني قغران"},
        {"id": 493, "n": "Ait Bouaddou", "ar": "أيت بــوادو"},
        {"id": 538, "n": "Ouadhias", "ar": "واضية"},
        {"id": 547, "n": "Tizi N'tleta", "ar": "تيزي نثلاثة"},
        {"id": 488, "n": "Aghribs", "ar": "أغريب"},
        {"id": 498, "n": "Ait-Chafaa", "ar": "أيت شافع"},
        {"id": 504, "n": "Akerrou", "ar": "أقرو"},
        {"id": 507, "n": "Azeffoun", "ar": "أزفون"},
        {"id": 525, "n": "Iflissen", "ar": "إفليـــسن"},
        {"id": 544, "n": "Tigzirt", "ar": "تيقـزيرت"},
        {"id": 505, "n": "Assi-Youcef", "ar": "أسي يوسف"},
        {"id": 513, "n": "Boghni", "ar": "بوغني"},
        {"id": 515, "n": "Bounouh", "ar": "بونوح"},
        {"id": 533, "n": "Mechtras", "ar": "مشطراس"},
        {"id": 517, "n": "Draa-Ben-Khedda", "ar": "ذراع بن خدة"},
        {"id": 540, "n": "Sidi Namane", "ar": "سيدي نعمان"},
        {"id": 543, "n": "Tadmait", "ar": "تادمايت"},
        {"id": 546, "n": "Tirmitine", "ar": "تيرمتين"},
        {"id": 494, "n": "Ait Boumahdi", "ar": "أيت بومهدي"},
        {"id": 501, "n": "Ait-Toudert", "ar": "أيت تودرت"},
        {"id": 509, "n": "Beni-Aissi", "ar": "بني عيسي"},
        {"id": 537, "n": "Ouacif", "ar": "واسيف"},
        {"id": 495, "n": "Ait Khellili", "ar": "أيت خليلي"},
        {"id": 534, "n": "Mekla", "ar": "مقــلع"},
        {"id": 541, "n": "Souama", "ar": "صوامـــع"},
        {"id": 511, "n": "Beni-Yenni", "ar": "بني يني"},
        {"id": 521, "n": "Iboudrarene", "ar": "إبودرارن"},
        {"id": 549, "n": "Tizi-Ouzou", "ar": "تيزي وزو"},
        {"id": 487, "n": "Abi-Youcef", "ar": "أبي يوسف"},
        {"id": 490, "n": "Ain-El-Hammam", "ar": "عين الحمام"},
        {"id": 502, "n": "Ait-Yahia", "ar": "أيت يحيى"},
        {"id": 503, "n": "Akbil", "ar": "اقبيل"},
        {"id": 514, "n": "Boudjima", "ar": "بوجيمة"},
        {"id": 532, "n": "Makouda", "ar": "ماكودة"},
        {"id": 491, "n": "Ain-Zaouia", "ar": "عين الزاوية"},
        {"id": 496, "n": "Ait Yahia Moussa", "ar": "أيت يحي موسى"},
        {"id": 518, "n": "Draa-El-Mizan", "ar": "ذراع الميزان"},
        {"id": 520, "n": "Frikat", "ar": "فريقات"},
        {"id": 536, "n": "M'kira", "ar": "مكيرة"},
        {"id": 548, "n": "Tizi-Gheniff", "ar": "تيزي غنيف"},
        {"id": 552, "n": "Yatafene", "ar": "يطــافن"},
        {"id": 526, "n": "Illilten", "ar": "إيلـيــلتـن"},
        {"id": 528, "n": "Imsouhal", "ar": "إمســوحال"},
        {"id": 506, "n": "Azazga", "ar": "عزازقة"},
        {"id": 519, "n": "Freha", "ar": "فريحة"},
        {"id": 524, "n": "Ifigha", "ar": "إيفيغاء"},
        {"id": 551, "n": "Yakourene", "ar": "إعــكورن"},
        {"id": 553, "n": "Zekri", "ar": "زكري"},
        {"id": 492, "n": "Ait Aggouacha", "ar": "أيت عقـواشة"},
        {"id": 529, "n": "Irdjen", "ar": "إيرجـــن"},
        {"id": 530, "n": "Larbaa Nath Irathen", "ar": "الأربعــاء ناث إيراثن"},
        {"id": 500, "n": "Ait-Oumalou", "ar": "أيت  أومالو"},
        {"id": 550, "n": "Tizi-Rached", "ar": "تيزي راشد"},
        {"id": 497, "n": "Ait-Aissa-Mimoun", "ar": "أيت عيسى ميمون"},
        {"id": 539, "n": "Ouaguenoun", "ar": "واقنون"},
        {"id": 545, "n": "Timizart", "ar": "تيمـيزار"},
        {"id": 531, "n": "Maatkas", "ar": "معـــاتقة"},
        {"id": 542, "n": "Souk-El-Tenine", "ar": "سوق الإثنين"},
        {"id": 499, "n": "Ait-Mahmoud", "ar": "أيت محمود"},
        {"id": 508, "n": "Beni Zmenzer", "ar": "بنــــي زمنزار"},
        {"id": 523, "n": "Iferhounene", "ar": "إفــرحــونان"},
        {"id": 516, "n": "Bouzeguene", "ar": "بوزقــن"}
      ]
    },
    "16": {
      "id": "16",
      "n": "Alger",
      "ar": "الجزائر",
      "c": [
        {"id": 588, "n": "Hussein Dey", "ar": "حسين داي"},
        {"id": 592, "n": "Les Eucalyptus", "ar": "الكاليتوس"},
        {"id": 606, "n": "Sidi Moussa", "ar": "سيدي موسى"},
        {"id": 591, "n": "Kouba", "ar": "القبة"},
        {"id": 594, "n": "Mohamed Belouzdad", "ar": "محمد بلوزداد"},
        {"id": 555, "n": "Ain Taya", "ar": "عين طاية"},
        {"id": 558, "n": "Bab Ezzouar", "ar": "باب الزوار"},
        {"id": 569, "n": "Bordj El Kiffan", "ar": "برج الكيفان"},
        {"id": 574, "n": "Dar El Beida", "ar": "الدار البيضاء"},
        {"id": 584, "n": "El Marsa", "ar": "المرسى"},
        {"id": 595, "n": "Mohammadia", "ar": "المحمدية"},
        {"id": 566, "n": "Bir Touta", "ar": "بئر توتة"},
        {"id": 598, "n": "Ouled Chebel", "ar": "اولاد شبل"},
        {"id": 609, "n": "Tessala El Merdja", "ar": "تسالة المرجة"},
        {"id": 587, "n": "Herraoua", "ar": "هراوة"},
        {"id": 602, "n": "Reghaia", "ar": "رغاية"},
        {"id": 603, "n": "Rouiba", "ar": "الرويبة"},
        {"id": 593, "n": "Maalma", "ar": "المعالمة"},
        {"id": 600, "n": "Rahmania", "ar": "الرحمانية"},
        {"id": 607, "n": "Souidania", "ar": "سويدانية"},
        {"id": 608, "n": "Staoueli", "ar": "سطاوالي"},
        {"id": 610, "n": "Zeralda", "ar": "زرالدة"},
        {"id": 559, "n": "Baba Hassen", "ar": "بابا حسن"},
        {"id": 577, "n": "Douira", "ar": "الدويرة"},
        {"id": 578, "n": "Draria", "ar": "الدرارية"},
        {"id": 579, "n": "El Achour", "ar": "العاشور"},
        {"id": 590, "n": "Khraissia", "ar": "الخرايسية"},
        {"id": 554, "n": "Ain Benian", "ar": "عين بنيان"},
        {"id": 573, "n": "Cheraga", "ar": "الشراقة"},
        {"id": 575, "n": "Dely Ibrahim", "ar": "دالي ابراهيم"},
        {"id": 586, "n": "Hammamet", "ar": "الحمامات"},
        {"id": 599, "n": "Ouled Fayet", "ar": "اولاد فايت"},
        {"id": 556, "n": "Alger Centre", "ar": "الجزائر الوسطى"},
        {"id": 582, "n": "El Madania", "ar": "المدنية"},
        {"id": 585, "n": "El Mouradia", "ar": "المرادية"},
        {"id": 605, "n": "Sidi M'hamed", "ar": "سيدي امحمد"},
        {"id": 604, "n": "Sehaoula", "ar": "السحاولة"},
        {"id": 567, "n": "Bologhine Ibnou Ziri", "ar": "بولوغين بن زيري"},
        {"id": 572, "n": "Casbah", "ar": "القصبة"},
        {"id": 596, "n": "Oued Koriche", "ar": "وادي قريش"},
        {"id": 601, "n": "Rais Hamidou", "ar": "الرايس حميدو"},
        {"id": 564, "n": "Bir Mourad Rais", "ar": "بئر مراد رايس"},
        {"id": 565, "n": "Birkhadem", "ar": "بئر خادم"},
        {"id": 576, "n": "Djasr Kasentina", "ar": "جسر قسنطينة"},
        {"id": 589, "n": "Hydra", "ar": "حيدرة"},
        {"id": 583, "n": "El Magharia", "ar": "المغارية"},
        {"id": 562, "n": "Ben Aknoun", "ar": "ابن عكنون"},
        {"id": 563, "n": "Beni Messous", "ar": "بني مسوس"},
        {"id": 571, "n": "Bouzareah", "ar": "بوزريعة"},
        {"id": 580, "n": "El Biar", "ar": "الابيار"},
        {"id": 560, "n": "Bachedjerah", "ar": "باش جراح"},
        {"id": 570, "n": "Bourouba", "ar": "بوروبة"},
        {"id": 581, "n": "El Harrach", "ar": "الحراش"},
        {"id": 597, "n": "Oued Smar", "ar": "وادي السمار"},
        {"id": 561, "n": "Baraki", "ar": "براقي"},
        {"id": 568, "n": "Bordj El Bahri", "ar": "برج البحري"},
        {"id": 557, "n": "Bab El Oued", "ar": "باب الوادي"}
      ]
    },
    "17": {
      "id": "17",
      "n": "Djelfa",
      "ar": "الجلفة",
      "c": [
        {"id": 634, "n": "Hassi El Euch", "ar": "حاسي العش"},
        {"id": 612, "n": "Ain El Ibel", "ar": "عين الإبل"},
        {"id": 626, "n": "El Guedid", "ar": "القديد"},
        {"id": 621, "n": "Charef", "ar": "الشارف"},
        {"id": 618, "n": "Benyagoub", "ar": "بن يعقوب"},
        {"id": 642, "n": "Sidi Baizid", "ar": "سيدي بايزيد"},
        {"id": 637, "n": "M'liliha", "ar": "مليليحة"},
        {"id": 622, "n": "Dar Chioukh", "ar": "دار الشيوخ"},
        {"id": 644, "n": "Taadmit", "ar": "تعظميت"},
        {"id": 632, "n": "Had Sahary", "ar": "حد الصحاري"},
        {"id": 620, "n": "Bouira Lahdab", "ar": "بويرة الأحداب"},
        {"id": 613, "n": "Ain Fekka", "ar": "عين فقه"},
        {"id": 643, "n": "Sidi Laadjel", "ar": "سيدي لعجال"},
        {"id": 635, "n": "Hassi Fedoul", "ar": "حاسي فدول"},
        {"id": 628, "n": "El Khemis", "ar": "الخميس"},
        {"id": 641, "n": "Selmana", "ar": "سلمانة"},
        {"id": 640, "n": "Sed Rahal", "ar": "سد الرحال"},
        {"id": 636, "n": "Messaad", "ar": "مسعد"},
        {"id": 631, "n": "Guettara", "ar": "قطارة"},
        {"id": 623, "n": "Deldoul", "ar": "دلدول"},
        {"id": 646, "n": "Zaccar", "ar": "زكار"},
        {"id": 625, "n": "Douis", "ar": "دويس"},
        {"id": 627, "n": "El Idrissia", "ar": "الادريسية"},
        {"id": 611, "n": "Ain Chouhada", "ar": "عين الشهداء"},
        {"id": 624, "n": "Djelfa", "ar": "الجلفة"},
        {"id": 619, "n": "Birine", "ar": "بيرين"},
        {"id": 639, "n": "Oum Laadham", "ar": "أم العظام"},
        {"id": 629, "n": "Faidh El Botma", "ar": "فيض البطمة"},
        {"id": 616, "n": "Amourah", "ar": "عمورة"},
        {"id": 645, "n": "Zaafrane", "ar": "زعفران"},
        {"id": 630, "n": "Guernini", "ar": "قرنيني"},
        {"id": 615, "n": "Ain Oussera", "ar": "عين وسارة"},
        {"id": 617, "n": "Benhar", "ar": "بنهار"},
        {"id": 614, "n": "Ain Maabed", "ar": "عين معبد"},
        {"id": 633, "n": "Hassi Bahbah", "ar": "حاسي بحبح"},
        {"id": 638, "n": "Moudjebara", "ar": "مجبارة"}
      ]
    },
    "18": {
      "id": "18",
      "n": "Jijel",
      "ar": "جيجل",
      "c": [
        {"id": 662, "n": "Jijel", "ar": "جيجل"},
        {"id": 656, "n": "El Aouana", "ar": "العوانة"},
        {"id": 668, "n": "Selma Benziada", "ar": "سلمى بن زيادة"},
        {"id": 660, "n": "Erraguene Souissi", "ar": "أراقن سويسي"},
        {"id": 650, "n": "Boussif Ouled Askeur", "ar": "بوسيف أولاد عسكر"},
        {"id": 674, "n": "Ziama Mansouriah", "ar": "زيامة منصورية"},
        {"id": 651, "n": "Chahna", "ar": "الشحنة"},
        {"id": 659, "n": "Emir Abdelkader", "ar": "الامير عبد القادر"},
        {"id": 665, "n": "Oudjana", "ar": "وجانة"},
        {"id": 672, "n": "Taher", "ar": "الطاهير"},
        {"id": 652, "n": "Chekfa", "ar": "الشقفة"},
        {"id": 657, "n": "El Kennar Nouchfi", "ar": "القنار نشفي"},
        {"id": 670, "n": "Sidi Abdelaziz", "ar": "سيدي عبد العزيز"},
        {"id": 658, "n": "El Milia", "ar": "الميلية"},
        {"id": 667, "n": "Ouled Yahia Khadrouch", "ar": "أولاد يحيى خدروش"},
        {"id": 666, "n": "Ouled Rabah", "ar": "أولاد رابح"},
        {"id": 671, "n": "Sidi Marouf", "ar": "سيدي معروف"},
        {"id": 661, "n": "Ghebala", "ar": "غبالة"},
        {"id": 669, "n": "Settara", "ar": "السطارة"},
        {"id": 649, "n": "Bouraoui Belhadef", "ar": "بوراوي بلهادف"},
        {"id": 655, "n": "El Ancer", "ar": "العنصر"},
        {"id": 664, "n": "Khiri Oued Adjoul", "ar": "خيري واد عجول"},
        {"id": 654, "n": "Djimla", "ar": "جيملة"},
        {"id": 663, "n": "Kaous", "ar": "قاوس"},
        {"id": 673, "n": "Texenna", "ar": "تاكسنة"},
        {"id": 647, "n": "Bordj T'har", "ar": "برج الطهر"},
        {"id": 648, "n": "Boudria Beniyadjis", "ar": "بودريعة بني  ياجيس"},
        {"id": 653, "n": "Djemaa Beni Habibi", "ar": "الجمعة بني حبيبي"}
      ]
    },
    "19": {
      "id": "19",
      "n": "Sétif",
      "ar": "سطيف",
      "c": [
        {"id": 726, "n": "Rosfa", "ar": "الرصفة"},
        {"id": 721, "n": "Oued El Bared", "ar": "واد البارد"},
        {"id": 734, "n": "Tizi N'bechar", "ar": "تيزي نبشار"},
        {"id": 720, "n": "Mezloug", "ar": "مزلوق"},
        {"id": 709, "n": "Guellal", "ar": "قلال"},
        {"id": 717, "n": "Kasr El Abtal", "ar": "قصر الابطال"},
        {"id": 724, "n": "Ouled Si Ahmed", "ar": "أولاد سي أحمد"},
        {"id": 684, "n": "Ait Naoual Mezada", "ar": "أيت نوال مزادة"},
        {"id": 685, "n": "Ait-Tizi", "ar": "ايت تيزي"},
        {"id": 699, "n": "Bouandas", "ar": "بوعنداس"},
        {"id": 701, "n": "Bousselam", "ar": "بوسلام"},
        {"id": 713, "n": "Hamam Soukhna", "ar": "حمام السخنة"},
        {"id": 732, "n": "Taya", "ar": "الطاية"},
        {"id": 733, "n": "Tella", "ar": "التلة"},
        {"id": 680, "n": "Ain Oulmene", "ar": "عين ولمان"},
        {"id": 702, "n": "Boutaleb", "ar": "بوطالب"},
        {"id": 714, "n": "Hamma", "ar": "الحامة"},
        {"id": 725, "n": "Ouled Tebben", "ar": "أولاد تبان"},
        {"id": 686, "n": "Amoucha", "ar": "عموشة"},
        {"id": 727, "n": "Salah Bey", "ar": "صالح باي"},
        {"id": 677, "n": "Ain Azel", "ar": "عين أزال"},
        {"id": 679, "n": "Ain Lahdjar", "ar": "عين الحجر"},
        {"id": 689, "n": "Beidha Bordj", "ar": "بيضاء برج"},
        {"id": 697, "n": "Bir Haddada", "ar": "بئر حدادة"},
        {"id": 711, "n": "Guenzet", "ar": "قنزات"},
        {"id": 716, "n": "Harbil", "ar": "حربيل"},
        {"id": 682, "n": "Ain-Roua", "ar": "عين الروى"},
        {"id": 694, "n": "Beni Oussine", "ar": "بني وسين"},
        {"id": 707, "n": "El Ouricia", "ar": "أوريسيا"},
        {"id": 700, "n": "Bougaa", "ar": "بوقاعة"},
        {"id": 705, "n": "Draa-Kebila", "ar": "ذراع قبيلة"},
        {"id": 715, "n": "Hammam Guergour", "ar": "حمام قرقور"},
        {"id": 729, "n": "Setif", "ar": "سطيف"},
        {"id": 678, "n": "Ain El Kebira", "ar": "عين الكبيرة"},
        {"id": 703, "n": "Dehamcha", "ar": "الدهامشة"},
        {"id": 722, "n": "Ouled Addouane", "ar": "أولاد عدوان"},
        {"id": 683, "n": "Ain-Sebt", "ar": "عين السبت"},
        {"id": 695, "n": "Beni-Aziz", "ar": "بني عزيز"},
        {"id": 718, "n": "Maaouia", "ar": "معاوية"},
        {"id": 690, "n": "Bellaa", "ar": "بلاعة"},
        {"id": 698, "n": "Bir-El-Arch", "ar": "بئر العرش"},
        {"id": 708, "n": "El-Ouldja", "ar": "الولجة"},
        {"id": 730, "n": "Tachouda", "ar": "تاشودة"},
        {"id": 731, "n": "Tala-Ifacene", "ar": "تالة إيفاسن"},
        {"id": 728, "n": "Serdj-El-Ghoul", "ar": "سرج الغول"},
        {"id": 712, "n": "Guidjel", "ar": "قجال"},
        {"id": 723, "n": "Ouled Sabor", "ar": "أولاد صابر"},
        {"id": 688, "n": "Bazer-Sakra", "ar": "بازر سكرة"},
        {"id": 706, "n": "El Eulma", "ar": "العلمة"},
        {"id": 710, "n": "Guelta Zerka", "ar": "قلتة زرقاء"},
        {"id": 692, "n": "Beni Fouda", "ar": "بني فودة"},
        {"id": 704, "n": "Djemila", "ar": "جميلة"},
        {"id": 681, "n": "Ain-Legradj", "ar": "عين لقراج"},
        {"id": 691, "n": "Beni Chebana", "ar": "بني شبانة"},
        {"id": 693, "n": "Beni Ourtilane", "ar": "بني ورتيلان"},
        {"id": 696, "n": "Beni-Mouhli", "ar": "بني موحلي"},
        {"id": 675, "n": "Ain Abessa", "ar": "عين عباسة"},
        {"id": 676, "n": "Ain Arnat", "ar": "عين أرنات"},
        {"id": 687, "n": "Babor", "ar": "بابور"},
        {"id": 719, "n": "Maouaklane", "ar": "ماوكلان"}
      ]
    },
    "20": {
      "id": "20",
      "n": "Saïda",
      "ar": "سعيدة",
      "c": [
        {"id": 745, "n": "Saida", "ar": "سعيدة"},
        {"id": 749, "n": "Tircine", "ar": "تيرسين"},
        {"id": 743, "n": "Ouled Brahim", "ar": "أولاد إبراهيم"},
        {"id": 737, "n": "Ain Soltane", "ar": "عين السلطان"},
        {"id": 741, "n": "Maamora", "ar": "المعمورة"},
        {"id": 739, "n": "El Hassasna", "ar": "الحساسنة"},
        {"id": 736, "n": "Ain Sekhouna", "ar": "عين السخونة"},
        {"id": 748, "n": "Sidi Boubekeur", "ar": "سيدي بوبكر"},
        {"id": 744, "n": "Ouled Khaled", "ar": "أولاد خالد"},
        {"id": 740, "n": "Hounet", "ar": "هونت"},
        {"id": 750, "n": "Youb", "ar": "يوب"},
        {"id": 738, "n": "Doui Thabet", "ar": "دوي ثابت"},
        {"id": 746, "n": "Sidi Ahmed", "ar": "سيدي احمد"},
        {"id": 742, "n": "Moulay Larbi", "ar": "مولاي العربي"},
        {"id": 735, "n": "Ain El Hadjar", "ar": "عين الحجر"},
        {"id": 747, "n": "Sidi Amar", "ar": "سيدي عمر"}
      ]
    },
    "21": {
      "id": "21",
      "n": "Skikda",
      "ar": "سكيكدة",
      "c": [
        {"id": 751, "n": "Ain Bouziane", "ar": "عين بوزيان"},
        {"id": 783, "n": "Salah Bouchaour", "ar": "صالح بو الشعور"},
        {"id": 768, "n": "El Hadaiek", "ar": "الحدائق"},
        {"id": 787, "n": "Zerdezas", "ar": "زردازة"},
        {"id": 780, "n": "Ouled Habbaba", "ar": "أولاد حبابة"},
        {"id": 759, "n": "Beni Oulbane", "ar": "بني ولبان"},
        {"id": 784, "n": "Sidi Mezghiche", "ar": "سيدي مزغيش"},
        {"id": 758, "n": "Beni Bechir", "ar": "بني بشير"},
        {"id": 782, "n": "Ramdane Djamel", "ar": "رمضان جمال"},
        {"id": 761, "n": "Bin El Ouiden", "ar": "بين الويدان"},
        {"id": 770, "n": "Emjez Edchich", "ar": "مجاز الدشيش"},
        {"id": 786, "n": "Tamalous", "ar": "تمالوس"},
        {"id": 753, "n": "Ain Kechra", "ar": "عين قشرة"},
        {"id": 778, "n": "Ouldja Boulbalout", "ar": "الولجة بولبلوط"},
        {"id": 781, "n": "Oum Toub", "ar": "أم الطوب"},
        {"id": 767, "n": "El Ghedir", "ar": "الغدير"},
        {"id": 775, "n": "Kerkara", "ar": "الكركرة"},
        {"id": 766, "n": "El Arrouch", "ar": "الحروش"},
        {"id": 788, "n": "Zitouna", "ar": "الزيتونة"},
        {"id": 779, "n": "Ouled Attia", "ar": "أولاد عطية"},
        {"id": 777, "n": "Oued Zhour", "ar": "وادي الزهور"},
        {"id": 764, "n": "Collo", "ar": "القل"},
        {"id": 763, "n": "Cheraia", "ar": "الشرايع"},
        {"id": 760, "n": "Beni Zid", "ar": "بني زيد"},
        {"id": 776, "n": "Khenag Maoune", "ar": "خناق مايو"},
        {"id": 769, "n": "El Marsa", "ar": "المرسى"},
        {"id": 757, "n": "Ben Azzouz", "ar": "بن عزوز"},
        {"id": 756, "n": "Bekkouche Lakhdar", "ar": "بكوش لخضر"},
        {"id": 771, "n": "Es Sebt", "ar": "السبت"},
        {"id": 752, "n": "Ain Charchar", "ar": "عين شرشار"},
        {"id": 755, "n": "Azzaba", "ar": "عزابة"},
        {"id": 762, "n": "Bouchetata", "ar": "بوشطاطة"},
        {"id": 772, "n": "Filfila", "ar": "فلفلة"},
        {"id": 773, "n": "Hammadi Krouma", "ar": "حمادي كرومة"},
        {"id": 785, "n": "Skikda", "ar": "سكيكدة"},
        {"id": 754, "n": "Ain Zouit", "ar": "عين زويت"},
        {"id": 765, "n": "Djendel Saadi Mohamed", "ar": "جندل سعدي محمد"},
        {"id": 774, "n": "Kanoua", "ar": "قنواع"}
      ]
    },
    "22": {
      "id": "22",
      "n": "Sidi Bel Abbès",
      "ar": "سيدي بلعباس",
      "c": [
        {"id": 822, "n": "Sidi Ali Benyoub", "ar": "سيدي علي بن يوب"},
        {"id": 814, "n": "Moulay Slissen", "ar": "مولاي سليسن"},
        {"id": 804, "n": "El Hacaiba", "ar": "الحصيبة"},
        {"id": 792, "n": "Ain Tindamine", "ar": "عين تندمين"},
        {"id": 837, "n": "Tenira", "ar": "تنيرة"},
        {"id": 816, "n": "Oued Sefioun", "ar": "وادي سفيون"},
        {"id": 805, "n": "Hassi Dahou", "ar": "حاسي دحو"},
        {"id": 817, "n": "Oued Taourira", "ar": "وادي تاوريرة"},
        {"id": 798, "n": "Benachiba Chelia", "ar": "بن عشيبة شلية"},
        {"id": 831, "n": "Sidi Yacoub", "ar": "سيدي يعقوب"},
        {"id": 830, "n": "Sidi Lahcene", "ar": "سيدي لحسن"},
        {"id": 829, "n": "Sidi Khaled", "ar": "سيدي خالد"},
        {"id": 832, "n": "Tabia", "ar": "طابية"},
        {"id": 825, "n": "Sidi Brahim", "ar": "سيدي ابراهيم"},
        {"id": 794, "n": "Amarnas", "ar": "العمارنة"},
        {"id": 801, "n": "Boukhanefis", "ar": "بوخنفيس"},
        {"id": 806, "n": "Hassi Zahana", "ar": "حاسي زهانة"},
        {"id": 802, "n": "Chetouane Belaila", "ar": "شيطوان البلايلة"},
        {"id": 797, "n": "Ben Badis", "ar": "بن باديس"},
        {"id": 795, "n": "Bedrabine El Mokrani", "ar": "بضرابين المقراني"},
        {"id": 821, "n": "Sfisef", "ar": "سفيزف"},
        {"id": 810, "n": "M'cid", "ar": "مسيد"},
        {"id": 800, "n": "Boudjebaa El Bordj", "ar": "بوجبهة البرج"},
        {"id": 793, "n": "Ain- Adden", "ar": "عين أدن"},
        {"id": 828, "n": "Sidi Hamadouche", "ar": "سيدي حمادوش"},
        {"id": 826, "n": "Sidi Chaib", "ar": "سيدي شعيب"},
        {"id": 808, "n": "Makedra", "ar": "مكدرة"},
        {"id": 789, "n": "Ain El Berd", "ar": "عين البرد"},
        {"id": 819, "n": "Redjem Demouche", "ar": "رجم دموش"},
        {"id": 818, "n": "Ras El Ma", "ar": "راس الماء"},
        {"id": 815, "n": "Oued Sebaa", "ar": "وادي السبع"},
        {"id": 809, "n": "Marhoum", "ar": "مرحوم"},
        {"id": 824, "n": "Sidi Bel-Abbes", "ar": "سيدي بلعباس"},
        {"id": 791, "n": "Ain Thrid", "ar": "عين الثريد"},
        {"id": 820, "n": "Sehala Thaoura", "ar": "السهالة الثورة"},
        {"id": 838, "n": "Tessala", "ar": "تسالة"},
        {"id": 796, "n": "Belarbi", "ar": "بلعربي"},
        {"id": 813, "n": "Mostefa  Ben Brahim", "ar": "مصطفى بن ابراهيم"},
        {"id": 839, "n": "Tilmouni", "ar": "تلموني"},
        {"id": 840, "n": "Zerouala", "ar": "زروالة"},
        {"id": 803, "n": "Dhaya", "ar": "الضاية"},
        {"id": 812, "n": "Mezaourou", "ar": "مزاورو"},
        {"id": 835, "n": "Teghalimet", "ar": "تغاليمت"},
        {"id": 836, "n": "Telagh", "ar": "تلاغ"},
        {"id": 790, "n": "Ain Kada", "ar": "عين قادة"},
        {"id": 807, "n": "Lamtar", "ar": "لمطار"},
        {"id": 823, "n": "Sidi Ali Boussidi", "ar": "سيدي علي بوسيدي"},
        {"id": 827, "n": "Sidi Dahou Zairs", "ar": "سيدي دحو الزاير"},
        {"id": 799, "n": "Bir El Hammam", "ar": "بئر الحمام"},
        {"id": 811, "n": "Merine", "ar": "مرين"},
        {"id": 834, "n": "Tefessour", "ar": "تفسور"},
        {"id": 833, "n": "Taoudmout", "ar": "تاودموت"}
      ]
    },
    "23": {
      "id": "23",
      "n": "Annaba",
      "ar": "عنابة",
      "c": [
        {"id": 842, "n": "Annaba", "ar": "عنابة"},
        {"id": 850, "n": "Seraidi", "ar": "سرايدي"},
        {"id": 843, "n": "Berrahal", "ar": "برحال"},
        {"id": 849, "n": "Oued El Aneb", "ar": "واد العنب"},
        {"id": 848, "n": "El Hadjar", "ar": "الحجار"},
        {"id": 851, "n": "Sidi Amar", "ar": "سيدي عمار"},
        {"id": 846, "n": "El Bouni", "ar": "البوني"},
        {"id": 841, "n": "Ain El Berda", "ar": "عين الباردة"},
        {"id": 845, "n": "Cheurfa", "ar": "الشرفة"},
        {"id": 847, "n": "El Eulma", "ar": "العلمة"},
        {"id": 852, "n": "Treat", "ar": "التريعات"},
        {"id": 844, "n": "Chetaibi", "ar": "شطايبي"}
      ]
    },
    "24": {
      "id": "24",
      "n": "Guelma",
      "ar": "قالمة",
      "c": [
        {"id": 875, "n": "Nechmaya", "ar": "نشماية"},
        {"id": 863, "n": "Bou Hamdane", "ar": "بوحمدان"},
        {"id": 872, "n": "Hammam Debagh", "ar": "حمام دباغ"},
        {"id": 884, "n": "Roknia", "ar": "الركنية"},
        {"id": 867, "n": "Dahouara", "ar": "الدهوارة"},
        {"id": 873, "n": "Hammam N'bail", "ar": "حمام النبايل"},
        {"id": 871, "n": "Guelma", "ar": "قالمة"},
        {"id": 866, "n": "Boumahra Ahmed", "ar": "بومهرة أحمد"},
        {"id": 853, "n": "Ain Ben Beida", "ar": "عين بن بيضاء"},
        {"id": 865, "n": "Bouchegouf", "ar": "بوشقوف"},
        {"id": 878, "n": "Medjez Sfa", "ar": "مجاز الصفاء"},
        {"id": 881, "n": "Oued Ferragha", "ar": "وادي فراغة"},
        {"id": 864, "n": "Bouati Mahmoud", "ar": "بوعاتي محمود"},
        {"id": 869, "n": "El Fedjoudj", "ar": "الفجوج"},
        {"id": 874, "n": "Heliopolis", "ar": "هيليوبوليس"},
        {"id": 877, "n": "Medjez Amar", "ar": "مجاز عمار"},
        {"id": 879, "n": "Houari Boumedienne", "ar": "هواري بومدين"},
        {"id": 883, "n": "Ras El Agba", "ar": "رأس العقبة"},
        {"id": 885, "n": "Sellaoua Announa", "ar": "سلاوة عنونة"},
        {"id": 868, "n": "Djeballah Khemissi", "ar": "جبالة الخميسي"},
        {"id": 861, "n": "Bordj Sabath", "ar": "برج صباط"},
        {"id": 882, "n": "Oued Zenati", "ar": "وادي الزناتي"},
        {"id": 856, "n": "Ain Regada", "ar": "عين رقادة"},
        {"id": 854, "n": "Ain Larbi", "ar": "عين العربي"},
        {"id": 855, "n": "Ain Makhlouf", "ar": "عين مخلوف"},
        {"id": 886, "n": "Tamlouka", "ar": "تاملوكة"},
        {"id": 857, "n": "Ain Sandel", "ar": "عين صندل"},
        {"id": 862, "n": "Bou Hachana", "ar": "بوحشانة"},
        {"id": 876, "n": "Khezaras", "ar": "لخزارة"},
        {"id": 858, "n": "Belkheir", "ar": "بلخير"},
        {"id": 860, "n": "Beni Mezline", "ar": "بني مزلين"},
        {"id": 870, "n": "Guelaat Bou Sbaa", "ar": "قلعة بوصبع"},
        {"id": 880, "n": "Oued Cheham", "ar": "وادي الشحم"},
        {"id": 859, "n": "Bendjarah", "ar": "بن جراح"}
      ]
    },
    "25": {
      "id": "25",
      "n": "Constantine",
      "ar": "قسنطينة",
      "c": [
        {"id": 892, "n": "Didouche Mourad", "ar": "ديدوش مراد"},
        {"id": 894, "n": "Hamma Bouziane", "ar": "حامة بوزيان"},
        {"id": 890, "n": "Beni Hamidane", "ar": "بني حميدان"},
        {"id": 898, "n": "Zighoud Youcef", "ar": "زيغود يوسف"},
        {"id": 888, "n": "Ain Smara", "ar": "عين السمارة"},
        {"id": 893, "n": "El Khroub", "ar": "الخروب"},
        {"id": 897, "n": "Ouled Rahmoun", "ar": "أولاد رحمون"},
        {"id": 887, "n": "Ain Abid", "ar": "عين عبيد"},
        {"id": 889, "n": "Ben Badis", "ar": "أبن باديس الهرية"},
        {"id": 895, "n": "Ibn Ziad", "ar": "ابن زياد"},
        {"id": 896, "n": "Messaoud Boudjeriou", "ar": "بوجريو مسعود"},
        {"id": 891, "n": "Constantine", "ar": "قسنطينة"}
      ]
    },
    "26": {
      "id": "26",
      "n": "Médéa",
      "ar": "المدية",
      "c": [
        {"id": 943, "n": "Ouled Hellal", "ar": "أولاد هلال"},
        {"id": 956, "n": "Souagui", "ar": "السواقي"},
        {"id": 929, "n": "Ksar El Boukhari", "ar": "قصر البخاري"},
        {"id": 934, "n": "M'fatha", "ar": "مفاتحة"},
        {"id": 947, "n": "Saneg", "ar": "السانق"},
        {"id": 920, "n": "El Azizia", "ar": "العزيزية"},
        {"id": 930, "n": "Maghraoua", "ar": "مغراوة"},
        {"id": 935, "n": "Mihoub", "ar": "ميهوب"},
        {"id": 909, "n": "Bouaiche", "ar": "بوعيش"},
        {"id": 912, "n": "Boughzoul", "ar": "بوغزول"},
        {"id": 914, "n": "Chabounia", "ar": "الشهبونية"},
        {"id": 926, "n": "Hannacha", "ar": "حناشة"},
        {"id": 936, "n": "Ouamri", "ar": "عوامري"},
        {"id": 937, "n": "Oued Harbil", "ar": "وادي حربيل"},
        {"id": 905, "n": "Beni Slimane", "ar": "بني سليمان"},
        {"id": 910, "n": "Bouaichoune", "ar": "بوعيشون"},
        {"id": 939, "n": "Ouled Bouachra", "ar": "أولاد بوعشرة"},
        {"id": 950, "n": "Si Mahdjoub", "ar": "سي المحجوب"},
        {"id": 913, "n": "Bouskene", "ar": "بوسكن"},
        {"id": 953, "n": "Sidi Rabie", "ar": "سيدي الربيع"},
        {"id": 906, "n": "Berrouaghia", "ar": "البرواقية"},
        {"id": 941, "n": "Ouled Deid", "ar": "أولاد دايد"},
        {"id": 946, "n": "Rebaia", "ar": "الربعية"},
        {"id": 932, "n": "Medjebar", "ar": "مجبر"},
        {"id": 961, "n": "Tletat Ed Douair", "ar": "ثلاث دوائر"},
        {"id": 962, "n": "Zoubiria", "ar": "الزبيرية"},
        {"id": 901, "n": "Aissaouia", "ar": "العيساوية"},
        {"id": 923, "n": "El Haoudane", "ar": "الحوضان"},
        {"id": 933, "n": "Mezerana", "ar": "مزغنة"},
        {"id": 957, "n": "Tablat", "ar": "تابلاط"},
        {"id": 908, "n": "Boghar", "ar": "بوغار"},
        {"id": 949, "n": "Seghouane", "ar": "سغوان"},
        {"id": 919, "n": "Draa Esmar", "ar": "ذراع السمار"},
        {"id": 931, "n": "Medea", "ar": "المدية"},
        {"id": 959, "n": "Tamesguida", "ar": "تمسقيدة"},
        {"id": 904, "n": "Ben Chicao", "ar": "بن شكاو"},
        {"id": 922, "n": "El Hamdania", "ar": "الحمدانية"},
        {"id": 945, "n": "Ouzera", "ar": "وزرة"},
        {"id": 960, "n": "Tizi Mahdi", "ar": "تيزي مهدي"},
        {"id": 899, "n": "Ain Boucif", "ar": "عين بوسيف"},
        {"id": 925, "n": "El Ouinet", "ar": "العوينات"},
        {"id": 927, "n": "Kef Lakhdar", "ar": "الكاف الاخضر"},
        {"id": 942, "n": "Ouled Emaaraf", "ar": "أولاد امعرف"},
        {"id": 951, "n": "Sidi Demed", "ar": "سيدي دامد"},
        {"id": 903, "n": "Baata", "ar": "بعطة"},
        {"id": 924, "n": "El Omaria", "ar": "العمارية"},
        {"id": 940, "n": "Ouled Brahim", "ar": "أولاد إبراهيم"},
        {"id": 907, "n": "Bir Ben Laabed", "ar": "بئر بن عابد"},
        {"id": 921, "n": "El Guelbelkebir", "ar": "القلب الكبير"},
        {"id": 948, "n": "Sedraya", "ar": "سدراية"},
        {"id": 900, "n": "Ain Ouksir", "ar": "عين اقصير"},
        {"id": 915, "n": "Chelalet El Adhaoura", "ar": "شلالة العذاورة"},
        {"id": 916, "n": "Cheniguel", "ar": "شنيقل"},
        {"id": 958, "n": "Tafraout", "ar": "تفراوت"},
        {"id": 911, "n": "Bouchrahil", "ar": "بوشراحيل"},
        {"id": 928, "n": "Khams Djouamaa", "ar": "خمس جوامع"},
        {"id": 952, "n": "Sidi Naamane", "ar": "سيدي نعمان"},
        {"id": 902, "n": "Aziz", "ar": "عزيز"},
        {"id": 917, "n": "Derrag", "ar": "دراق"},
        {"id": 944, "n": "Oum El Djellil", "ar": "أم الجليل"},
        {"id": 918, "n": "Djouab", "ar": "جواب"},
        {"id": 954, "n": "Sidi Zahar", "ar": "سيدي زهار"},
        {"id": 955, "n": "Sidi Ziane", "ar": "سيدي زيان"},
        {"id": 938, "n": "Ouled Antar", "ar": "أولاد عنتر"}
      ]
    },
    "27": {
      "id": "27",
      "n": "Mostaganem",
      "ar": "مستغانم",
      "c": [
        {"id": 970, "n": "Fornaka", "ar": "فرناقة"},
        {"id": 981, "n": "Oued El Kheir", "ar": "وادي الخير"},
        {"id": 973, "n": "Hassiane", "ar": "الحسيان (بني ياحي"},
        {"id": 972, "n": "Hassi Mameche", "ar": "حاسي ماماش"},
        {"id": 977, "n": "Mazagran", "ar": "مزغران"},
        {"id": 992, "n": "Stidia", "ar": "ستيدية"},
        {"id": 967, "n": "Ain-Tedles", "ar": "عين تادلس"},
        {"id": 987, "n": "Sidi Belaattar", "ar": "سيدي بلعطار"},
        {"id": 991, "n": "Sour", "ar": "سور"},
        {"id": 964, "n": "Ain-Boudinar", "ar": "عين بودينار"},
        {"id": 975, "n": "Kheir-Eddine", "ar": "خير الدين"},
        {"id": 985, "n": "Sayada", "ar": "صيادة"},
        {"id": 986, "n": "Sidi Ali", "ar": "سيدي علي"},
        {"id": 993, "n": "Tazgait", "ar": "تزقايت"},
        {"id": 968, "n": "Benabdelmalek Ramdane", "ar": "بن عبد المالك رمضان"},
        {"id": 979, "n": "Mostaganem", "ar": "مستغانم"},
        {"id": 971, "n": "Hadjadj", "ar": "حجاج"},
        {"id": 988, "n": "Sidi-Lakhdar", "ar": "سيدي لخضر"},
        {"id": 963, "n": "Achaacha", "ar": "عشعاشة"},
        {"id": 974, "n": "Khadra", "ar": "خضرة"},
        {"id": 980, "n": "Nekmaria", "ar": "نكمارية"},
        {"id": 982, "n": "Ouled Boughalem", "ar": "أولاد بوغالم"},
        {"id": 969, "n": "Bouguirat", "ar": "بوقيراط"},
        {"id": 984, "n": "Safsaf", "ar": "صفصاف"},
        {"id": 989, "n": "Sirat", "ar": "سيرات"},
        {"id": 990, "n": "Souaflia", "ar": "السوافلية"},
        {"id": 966, "n": "Ain-Sidi Cherif", "ar": "عين سيدي الشريف"},
        {"id": 976, "n": "Mansourah", "ar": "منصورة"},
        {"id": 978, "n": "Mesra", "ar": "ماسرة"},
        {"id": 994, "n": "Touahria", "ar": "الطواهرية"},
        {"id": 965, "n": "Ain-Nouissy", "ar": "عين نويسي"},
        {"id": 983, "n": "Ouled-Maalah", "ar": "أولاد مع الله"}
      ]
    },
    "28": {
      "id": "28",
      "n": "M'Sila",
      "ar": "المسيلة",
      "c": [
        {"id": 1008, "n": "Chellal", "ar": "شلال"},
        {"id": 1028, "n": "Ouled Madhi", "ar": "أولاد ماضي"},
        {"id": 1014, "n": "Khettouti Sed-El-Jir", "ar": "خطوطي سد الجير"},
        {"id": 1000, "n": "Belaiba", "ar": "بلعايبة"},
        {"id": 1004, "n": "Berhoum", "ar": "برهوم"},
        {"id": 1009, "n": "Dehahna", "ar": "دهاهنة"},
        {"id": 1018, "n": "Magra", "ar": "مقرة"},
        {"id": 1002, "n": "Beni Ilmane", "ar": "بني يلمان"},
        {"id": 1007, "n": "Bouti Sayeh", "ar": "بوطي السايح"},
        {"id": 1033, "n": "Sidi Aissa", "ar": "سيدي عيسى"},
        {"id": 995, "n": "Ain El Hadjel", "ar": "عين الحجل"},
        {"id": 1035, "n": "Sidi Hadjeres", "ar": "سيدي هجرس"},
        {"id": 1006, "n": "Bou Saada", "ar": "بوسعادة"},
        {"id": 1011, "n": "El Hamel", "ar": "الهامل"},
        {"id": 1032, "n": "Oulteme", "ar": "ولتام"},
        {"id": 1003, "n": "Benzouh", "ar": "بن زوه"},
        {"id": 1030, "n": "Ouled Sidi Brahim", "ar": "أولاد سيدي ابراهيم"},
        {"id": 1034, "n": "Sidi Ameur", "ar": "سيدي عامر"},
        {"id": 1039, "n": "Tamsa", "ar": "تامسة"},
        {"id": 1001, "n": "Ben Srour", "ar": "بن سرور"},
        {"id": 1022, "n": "Mohamed Boudiaf", "ar": "محمد بوضياف"},
        {"id": 1031, "n": "Ouled Slimane", "ar": "أولاد سليمان"},
        {"id": 1041, "n": "Zarzour", "ar": "زرزور"},
        {"id": 996, "n": "Ain El Melh", "ar": "عين الملح"},
        {"id": 997, "n": "Ain Fares", "ar": "عين فارس"},
        {"id": 999, "n": "Ain Rich", "ar": "عين الريش"},
        {"id": 1005, "n": "Bir Foda", "ar": "بئر فضة"},
        {"id": 1036, "n": "Sidi M'hamed", "ar": "سيدي امحمد"},
        {"id": 1020, "n": "Medjedel", "ar": "امجدل"},
        {"id": 1021, "n": "Menaa", "ar": "مناعة"},
        {"id": 1010, "n": "Djebel Messaad", "ar": "جبل مساعد"},
        {"id": 1037, "n": "Slim", "ar": "سليم"},
        {"id": 1023, "n": "M'sila", "ar": "المسيلة"},
        {"id": 1013, "n": "Hammam Dalaa", "ar": "حمام الضلعة"},
        {"id": 1025, "n": "Ouanougha", "ar": "ونوغة"},
        {"id": 1029, "n": "Ouled Mansour", "ar": "أولاد منصور"},
        {"id": 1040, "n": "Tarmount", "ar": "تارمونت"},
        {"id": 1016, "n": "Maadid", "ar": "المعاضيد"},
        {"id": 1024, "n": "M'tarfa", "ar": "المطارفة"},
        {"id": 1017, "n": "Maarif", "ar": "معاريف"},
        {"id": 1027, "n": "Ouled Derradj", "ar": "أولاد دراج"},
        {"id": 1038, "n": "Souamaa", "ar": "السوامع"},
        {"id": 1012, "n": "El Houamed", "ar": "الحوامد"},
        {"id": 1015, "n": "Khoubana", "ar": "خبانة"},
        {"id": 1019, "n": "M'cif", "ar": "مسيف"},
        {"id": 998, "n": "Ain Khadra", "ar": "عين الخضراء"},
        {"id": 1026, "n": "Ouled Addi Guebala", "ar": "أولاد عدي لقبالة"}
      ]
    },
    "29": {
      "id": "29",
      "n": "Mascara",
      "ar": "معسكر",
      "c": [
        {"id": 1075, "n": "Oued El Abtal", "ar": "وادي الأبطال"},
        {"id": 1081, "n": "Sidi Abdelmoumene", "ar": "سيدي عبد المومن"},
        {"id": 1078, "n": "Sedjerara", "ar": "سجرارة"},
        {"id": 1072, "n": "Mohammadia", "ar": "المحمدية"},
        {"id": 1085, "n": "Tighennif", "ar": "تيغنيف"},
        {"id": 1071, "n": "Mocta-Douz", "ar": "مقطع الدوز"},
        {"id": 1060, "n": "Ferraguig", "ar": "فراقيق"},
        {"id": 1054, "n": "El Ghomri", "ar": "الغمري"},
        {"id": 1087, "n": "Zahana", "ar": "زهانة"},
        {"id": 1053, "n": "El Gaada", "ar": "القعدة"},
        {"id": 1077, "n": "Ras El Ain Amirouche", "ar": "رأس عين عميروش"},
        {"id": 1074, "n": "Oggaz", "ar": "عقاز"},
        {"id": 1046, "n": "Alaimia", "ar": "العلايمية"},
        {"id": 1084, "n": "Sig", "ar": "سيق"},
        {"id": 1051, "n": "Chorfa", "ar": "الشرفاء"},
        {"id": 1049, "n": "Bou Henni", "ar": "بوهني"},
        {"id": 1058, "n": "El Mamounia", "ar": "المأمونية"},
        {"id": 1055, "n": "El Gueitena", "ar": "القطنة"},
        {"id": 1042, "n": "Ain Fares", "ar": "عين فارس"},
        {"id": 1062, "n": "Gharrous", "ar": "غروس"},
        {"id": 1048, "n": "Benian", "ar": "بنيان"},
        {"id": 1047, "n": "Aouf", "ar": "عوف"},
        {"id": 1064, "n": "Guerdjoum", "ar": "قرجوم"},
        {"id": 1045, "n": "Ain Frass", "ar": "عين أفرص"},
        {"id": 1043, "n": "Ain Fekan", "ar": "عين فكان"},
        {"id": 1066, "n": "Khalouia", "ar": "خلوية"},
        {"id": 1059, "n": "El Menaouer", "ar": "المنور"},
        {"id": 1052, "n": "El Bordj", "ar": "البرج"},
        {"id": 1082, "n": "Sidi Boussaid", "ar": "سيدي بوسعيد"},
        {"id": 1070, "n": "Matemore", "ar": "المطمور"},
        {"id": 1083, "n": "Sidi Kada", "ar": "سيدي قادة"},
        {"id": 1067, "n": "Makhda", "ar": "ماقضة"},
        {"id": 1069, "n": "Mascara", "ar": "معسكر"},
        {"id": 1050, "n": "Bouhanifia", "ar": "بوحنيفية"},
        {"id": 1063, "n": "Ghriss", "ar": "غريس"},
        {"id": 1065, "n": "Hacine", "ar": "حسين"},
        {"id": 1057, "n": "El Keurt", "ar": "القرط"},
        {"id": 1061, "n": "Froha", "ar": "فروحة"},
        {"id": 1086, "n": "Tizi", "ar": "تيزي"},
        {"id": 1079, "n": "Sehailia", "ar": "السهايلية"},
        {"id": 1068, "n": "Maoussa", "ar": "ماوسة"},
        {"id": 1080, "n": "Sidi Abdeldjebar", "ar": "سيدي عبد الجبار"},
        {"id": 1056, "n": "El Hachem", "ar": "الحشم"},
        {"id": 1073, "n": "Nesmot", "ar": "نسمط"},
        {"id": 1088, "n": "Zelamta", "ar": "زلامطة"},
        {"id": 1044, "n": "Ain Ferah", "ar": "عين فراح"},
        {"id": 1076, "n": "Oued Taria", "ar": "وادي التاغية"}
      ]
    },
    "30": {
      "id": "30",
      "n": "Ouargla",
      "ar": "ورقلة",
      "c": [
        {"id": 1101, "n": "Ouargla", "ar": "ورقلة"},
        {"id": 1096, "n": "Hassi Messaoud", "ar": "حاسي مسعود"},
        {"id": 1089, "n": "Ain Beida", "ar": "عين البيضاء"},
        {"id": 1095, "n": "Hassi Ben Abdellah", "ar": "حاسي بن عبد الله"},
        {"id": 1103, "n": "Sidi Khouiled", "ar": "سيدي خويلد"},
        {"id": 1093, "n": "El Borma", "ar": "البرمة"},
        {"id": 1102, "n": "Rouissat", "ar": "الرويسات"},
        {"id": 1100, "n": "N'goussa", "ar": "انقوسة"}
      ]
    },
    "31": {
      "id": "31",
      "n": "Oran",
      "ar": "وهران",
      "c": [
        {"id": 1134, "n": "Sidi Chami", "ar": "سيدي الشحمي"},
        {"id": 1127, "n": "Hassi Mefsoukh", "ar": "حاسي مفسوخ"},
        {"id": 1116, "n": "Bir El Djir", "ar": "بئر الجير"},
        {"id": 1125, "n": "Hassi Ben Okba", "ar": "حاسي بن عقبة"},
        {"id": 1124, "n": "Gdyel", "ar": "قديل"},
        {"id": 1126, "n": "Hassi Bounif", "ar": "حاسي بونيف"},
        {"id": 1122, "n": "El Kerma", "ar": "الكرمة"},
        {"id": 1123, "n": "Es Senia", "ar": "السانية"},
        {"id": 1114, "n": "Ben Freha", "ar": "بن فريحة"},
        {"id": 1113, "n": "Arzew", "ar": "أرزيو"},
        {"id": 1133, "n": "Sidi Ben Yebka", "ar": "سيدي بن يبقى"},
        {"id": 1110, "n": "Ain Biya", "ar": "عين البية"},
        {"id": 1115, "n": "Bethioua", "ar": "بطيوة"},
        {"id": 1128, "n": "Marsat El Hadjadj", "ar": "مرسى الحجاج"},
        {"id": 1112, "n": "Ain Turk", "ar": "عين الترك"},
        {"id": 1131, "n": "Oran", "ar": "وهران"},
        {"id": 1120, "n": "El Ancor", "ar": "العنصر"},
        {"id": 1129, "n": "Mers El Kebir", "ar": "المرسى الكبير"},
        {"id": 1117, "n": "Boufatis", "ar": "بوفاتيس"},
        {"id": 1121, "n": "El Braya", "ar": "البراية"},
        {"id": 1132, "n": "Oued Tlelat", "ar": "وادي تليلات"},
        {"id": 1111, "n": "Ain Kerma", "ar": "عين الكرمة"},
        {"id": 1119, "n": "Boutlelis", "ar": "بوتليليس"},
        {"id": 1130, "n": "Messerghin", "ar": "مسرغين"},
        {"id": 1118, "n": "Bousfer", "ar": "بوسفر"},
        {"id": 1135, "n": "Tafraoui", "ar": "طفراوي"}
      ]
    },
    "32": {
      "id": "32",
      "n": "El Bayadh",
      "ar": "البيض",
      "c": [
        {"id": 1136, "n": "Ain El Orak", "ar": "عين العراك"},
        {"id": 1151, "n": "Krakda", "ar": "كراكدة"},
        {"id": 1154, "n": "Sidi Slimane", "ar": "سيدي سليمان"},
        {"id": 1153, "n": "Sidi Ameur", "ar": "سيدي عامر"},
        {"id": 1138, "n": "Boualem", "ar": "بوعلام"},
        {"id": 1146, "n": "El Bnoud", "ar": "البنود"},
        {"id": 1139, "n": "Bougtoub", "ar": "بوقطب"},
        {"id": 1147, "n": "El Kheiter", "ar": "الخيثر"},
        {"id": 1157, "n": "Tousmouline", "ar": "توسمولين"},
        {"id": 1155, "n": "Sidi Tiffour", "ar": "سيدي طيفور"},
        {"id": 1156, "n": "Stitten", "ar": "ستيتن"},
        {"id": 1144, "n": "El Bayadh", "ar": "البيض"},
        {"id": 1152, "n": "Rogassa", "ar": "رقاصة"},
        {"id": 1148, "n": "El Mehara", "ar": "المحرة"},
        {"id": 1150, "n": "Kef El Ahmar", "ar": "الكاف الأحمر"},
        {"id": 1141, "n": "Brezina", "ar": "بريزينة"},
        {"id": 1149, "n": "Ghassoul", "ar": "الغاسول"},
        {"id": 1145, "n": "Labiodh Sidi Cheikh", "ar": "الأبيض سيدي الشيخ"},
        {"id": 1140, "n": "Boussemghoun", "ar": "بوسمغون"},
        {"id": 1142, "n": "Cheguig", "ar": "الشقيق"},
        {"id": 1143, "n": "Chellala", "ar": "شلالة"},
        {"id": 1137, "n": "Arbaouat", "ar": "اربوات"}
      ]
    },
    "33": {
      "id": "33",
      "n": "Illizi",
      "ar": "إليزي",
      "c": [
        {"id": 1159, "n": "Bordj Omar Driss", "ar": "برج عمر إدريس"},
        {"id": 1160, "n": "Debdeb", "ar": "دبداب"},
        {"id": 1163, "n": "In Amenas", "ar": "إن أمناس"},
        {"id": 1162, "n": "Illizi", "ar": "إيليزي"}
      ]
    },
    "34": {
      "id": "34",
      "n": "Bordj Bou Arreridj",
      "ar": "برج بوعريريج",
      "c": [
        {"id": 1177, "n": "Elhammadia", "ar": "الحمادية"},
        {"id": 1189, "n": "Ouled Sidi-Brahim", "ar": "أولاد سيدي ابراهيم"},
        {"id": 1164, "n": "Ain Taghrout", "ar": "عين تاغروت"},
        {"id": 1197, "n": "Tixter", "ar": "تيكستار"},
        {"id": 1167, "n": "Belimour", "ar": "بليمور"},
        {"id": 1176, "n": "El Annasseur", "ar": "العناصر"},
        {"id": 1180, "n": "Ghailasa", "ar": "غيلاسة"},
        {"id": 1194, "n": "Taglait", "ar": "تقلعيت"},
        {"id": 1170, "n": "Bordj Ghedir", "ar": "برج الغدير"},
        {"id": 1174, "n": "El Euch", "ar": "العش"},
        {"id": 1192, "n": "Sidi-Embarek", "ar": "سيدي أمبارك"},
        {"id": 1183, "n": "Khelil", "ar": "خليل"},
        {"id": 1169, "n": "Bir Kasdali", "ar": "بئر قاصد علي"},
        {"id": 1193, "n": "Tefreg", "ar": "تفرق"},
        {"id": 1178, "n": "El Main", "ar": "الماين"},
        {"id": 1173, "n": "Djaafra", "ar": "جعافرة"},
        {"id": 1172, "n": "Colla", "ar": "القلة"},
        {"id": 1196, "n": "Teniet En Nasr", "ar": "ثنية النصر"},
        {"id": 1179, "n": "El M'hir", "ar": "المهير"},
        {"id": 1184, "n": "Ksour", "ar": "القصور"},
        {"id": 1185, "n": "Mansoura", "ar": "المنصورة"},
        {"id": 1181, "n": "Haraza", "ar": "حرازة"},
        {"id": 1190, "n": "Rabta", "ar": "الرابطة"},
        {"id": 1175, "n": "El Achir", "ar": "الياشير"},
        {"id": 1182, "n": "Hasnaoua", "ar": "حسناوة"},
        {"id": 1186, "n": "Medjana", "ar": "مجانة"},
        {"id": 1165, "n": "Ain Tesra", "ar": "عين تسرة"},
        {"id": 1187, "n": "Ouled Brahem", "ar": "أولاد أبراهم"},
        {"id": 1191, "n": "Ras El Oued", "ar": "رأس الوادي"},
        {"id": 1171, "n": "Bordj Zemmoura", "ar": "برج زمورة"},
        {"id": 1188, "n": "Ouled Dahmane", "ar": "أولاد دحمان"},
        {"id": 1195, "n": "Tassamert", "ar": "تسامرت"},
        {"id": 1166, "n": "B. B. Arreridj", "ar": "برج بوعريرج"},
        {"id": 1168, "n": "Ben Daoud", "ar": "بن داود"}
      ]
    },
    "35": {
      "id": "35",
      "n": "Boumerdès",
      "ar": "بومرداس",
      "c": [
        {"id": 1212, "n": "El Kharrouba", "ar": "الخروبة"},
        {"id": 1210, "n": "Dellys", "ar": "دلس"},
        {"id": 1201, "n": "Ben Choud", "ar": "بن شود"},
        {"id": 1198, "n": "Afir", "ar": "أعفير"},
        {"id": 1226, "n": "Thenia", "ar": "الثنية"},
        {"id": 1202, "n": "Beni Amrane", "ar": "بني عمران"},
        {"id": 1215, "n": "Khemis El Khechna", "ar": "خميس الخشنة"},
        {"id": 1199, "n": "Ammal", "ar": "عمال"},
        {"id": 1228, "n": "Timezrit", "ar": "تيمزريت"},
        {"id": 1229, "n": "Zemmouri", "ar": "زموري"},
        {"id": 1216, "n": "Larbatache", "ar": "الاربعطاش"},
        {"id": 1214, "n": "Isser", "ar": "يسر"},
        {"id": 1208, "n": "Chabet El Ameur", "ar": "شعبة العامر"},
        {"id": 1219, "n": "Ouled Aissa", "ar": "أولاد عيسى"},
        {"id": 1218, "n": "Naciria", "ar": "الناصرية"},
        {"id": 1207, "n": "Bouzegza Keddara", "ar": "بوزقزة قدارة"},
        {"id": 1224, "n": "Souk El Had", "ar": "سوق الحد"},
        {"id": 1223, "n": "Sidi Daoud", "ar": "سيدي داود"},
        {"id": 1200, "n": "Baghlia", "ar": "بغلية"},
        {"id": 1217, "n": "Leghata", "ar": "لقاطة"},
        {"id": 1211, "n": "Djinet", "ar": "جنات"},
        {"id": 1227, "n": "Tidjelabine", "ar": "تيجلابين"},
        {"id": 1222, "n": "Si Mustapha", "ar": "سي مصطفى"},
        {"id": 1220, "n": "Ouled Hedadj", "ar": "أولاد هداج"},
        {"id": 1221, "n": "Ouled Moussa", "ar": "أولاد موسى"},
        {"id": 1206, "n": "Boumerdes", "ar": "بومرداس"},
        {"id": 1209, "n": "Corso", "ar": "قورصو"},
        {"id": 1203, "n": "Bordj Menaiel", "ar": "برج منايل"},
        {"id": 1204, "n": "Boudouaou", "ar": "بودواو"},
        {"id": 1205, "n": "Boudouaou El Bahri", "ar": "بودواو البحري"},
        {"id": 1225, "n": "Taourga", "ar": "تاورقة"},
        {"id": 1213, "n": "Hammedi", "ar": "حمادي"}
      ]
    },
    "36": {
      "id": "36",
      "n": "El Tarf",
      "ar": "الطارف",
      "c": [
        {"id": 1230, "n": "Ain El Assel", "ar": "عين العسل"},
        {"id": 1236, "n": "Bougous", "ar": "بوقوس"},
        {"id": 1246, "n": "El Tarf", "ar": "الطارف"},
        {"id": 1253, "n": "Zitouna", "ar": "الزيتونة"},
        {"id": 1235, "n": "Besbes", "ar": "البسباس"},
        {"id": 1231, "n": "Ain Kerma", "ar": "عين الكرمة"},
        {"id": 1237, "n": "Bouhadjar", "ar": "بوحجار"},
        {"id": 1247, "n": "Hammam Beni Salah", "ar": "حمام بني صالح"},
        {"id": 1249, "n": "Oued Zitoun", "ar": "وادي الزيتون"},
        {"id": 1233, "n": "Ben M Hidi", "ar": "بن مهيدي"},
        {"id": 1234, "n": "Berrihane", "ar": "بريحان"},
        {"id": 1239, "n": "Chebaita Mokhtar", "ar": "شبيطة مختار"},
        {"id": 1243, "n": "Echatt", "ar": "الشط"},
        {"id": 1244, "n": "El Aioun", "ar": "العيون"},
        {"id": 1245, "n": "El Kala", "ar": "القالة"},
        {"id": 1251, "n": "Souarekh", "ar": "السوارخ"},
        {"id": 1252, "n": "Zerizer", "ar": "زريزر"},
        {"id": 1238, "n": "Bouteldja", "ar": "بوثلجة"},
        {"id": 1240, "n": "Chefia", "ar": "الشافية"},
        {"id": 1248, "n": "Lac Des Oiseaux", "ar": "بحيرة الطيور"},
        {"id": 1241, "n": "Chihani", "ar": "شحاني"},
        {"id": 1250, "n": "Raml Souk", "ar": "رمل السوق"},
        {"id": 1232, "n": "Asfour", "ar": "عصفور"},
        {"id": 1242, "n": "Drean", "ar": "الذرعـان"}
      ]
    },
    "37": {
      "id": "37",
      "n": "Tindouf",
      "ar": "تندوف",
      "c": [
        {"id": 1255, "n": "Tindouf", "ar": "تندوف"},
        {"id": 1254, "n": "Oum El Assel", "ar": "أم العسل"}
      ]
    },
    "38": {
      "id": "38",
      "n": "Tissemsilt",
      "ar": "تيسمسيلت",
      "c": [
        {"id": 1262, "n": "Khemisti", "ar": "خميستي"},
        {"id": 1275, "n": "Theniet El Had", "ar": "ثنية الاحد"},
        {"id": 1269, "n": "Ouled Bessam", "ar": "أولاد بسام"},
        {"id": 1271, "n": "Sidi Boutouchent", "ar": "سيدي بوتوشنت"},
        {"id": 1276, "n": "Tissemsilt", "ar": "تيسمسيلت"},
        {"id": 1272, "n": "Sidi Lantri", "ar": "سيدي العنتري"},
        {"id": 1257, "n": "Beni Chaib", "ar": "بني شعيب"},
        {"id": 1258, "n": "Beni Lahcene", "ar": "بني لحسن"},
        {"id": 1270, "n": "Sidi Abed", "ar": "سيدي عابد"},
        {"id": 1273, "n": "Sidi Slimane", "ar": "سيدي سليمان"},
        {"id": 1261, "n": "Boucaid", "ar": "بوقائد"},
        {"id": 1263, "n": "Larbaa", "ar": "الأربعاء"},
        {"id": 1266, "n": "Lazharia", "ar": "الأزهرية"},
        {"id": 1264, "n": "Lardjem", "ar": "لرجام"},
        {"id": 1268, "n": "Melaab", "ar": "الملعب"},
        {"id": 1265, "n": "Layoune", "ar": "العيون"},
        {"id": 1274, "n": "Tamellahet", "ar": "تملاحت"},
        {"id": 1277, "n": "Youssoufia", "ar": "اليوسفية"},
        {
          "id": 1260,
          "n": "Bordj El Emir Abdelkader",
          "ar": "برج الأمير عبد القادر"
        },
        {"id": 1256, "n": "Ammari", "ar": "عماري"},
        {"id": 1267, "n": "Maacem", "ar": "المعاصم"},
        {"id": 1259, "n": "Bordj Bounaama", "ar": "برج بونعامة"}
      ]
    },
    "39": {
      "id": "39",
      "n": "El Oued",
      "ar": "الوادي",
      "c": [
        {"id": 1282, "n": "Douar El Maa", "ar": "دوار الماء"},
        {"id": 1283, "n": "El Ogla", "ar": "العقلة"},
        {"id": 1291, "n": "Magrane", "ar": "المقرن"},
        {"id": 1301, "n": "Sidi Aoun", "ar": "سيدي عون"},
        {"id": 1292, "n": "Mih Ouansa", "ar": "اميه وانسة"},
        {"id": 1290, "n": "Kouinine", "ar": "كوينين"},
        {"id": 1278, "n": "Bayadha", "ar": "البياضة"},
        {"id": 1294, "n": "Nakhla", "ar": "النخلة"},
        {"id": 1299, "n": "Robbah", "ar": "الرباح"},
        {"id": 1286, "n": "Guemar", "ar": "قمار"},
        {"id": 1279, "n": "Ben Guecha", "ar": "بن  قشة"},
        {"id": 1297, "n": "Ourmes", "ar": "ورماس"},
        {"id": 1304, "n": "Taghzout", "ar": "تغزوت"},
        {"id": 1287, "n": "Hamraia", "ar": "الحمراية"},
        {"id": 1298, "n": "Reguiba", "ar": "الرقيبة"},
        {"id": 1280, "n": "Debila", "ar": "الدبيلة"},
        {"id": 1288, "n": "Hassani Abdelkrim", "ar": "حساني عبد الكريم"},
        {"id": 1289, "n": "Hassi Khalifa", "ar": "حاسي خليفة"},
        {"id": 1307, "n": "Trifaoui", "ar": "الطريفاوي"},
        {"id": 1305, "n": "Taleb Larbi", "ar": "الطالب العربي"},
        {"id": 1295, "n": "Oued El Alenda", "ar": "وادي العلندة"},
        {"id": 1285, "n": "El-Oued", "ar": "الوادي"}
      ]
    },
    "40": {
      "id": "40",
      "n": "Khenchela",
      "ar": "خنشلة",
      "c": [
        {"id": 1321, "n": "Khirane", "ar": "خيران"},
        {"id": 1309, "n": "Babar", "ar": "بابار"},
        {"id": 1316, "n": "El Mahmal", "ar": "المحمل"},
        {"id": 1324, "n": "Ouled Rechache", "ar": "أولاد رشاش"},
        {"id": 1314, "n": "Djellal", "ar": "جلال"},
        {"id": 1328, "n": "Yabous", "ar": "يابوس"},
        {"id": 1320, "n": "Khenchela", "ar": "خنشلة"},
        {"id": 1319, "n": "Kais", "ar": "قايس"},
        {"id": 1313, "n": "Chelia", "ar": "شلية"},
        {"id": 1325, "n": "Remila", "ar": "الرميلة"},
        {"id": 1327, "n": "Taouzianat", "ar": "تاوزيانت"},
        {"id": 1310, "n": "Baghai", "ar": "بغاي"},
        {"id": 1315, "n": "El Hamma", "ar": "الحامة"},
        {"id": 1318, "n": "Ensigha", "ar": "انسيغة"},
        {"id": 1326, "n": "Tamza", "ar": "طامزة"},
        {"id": 1308, "n": "Ain Touila", "ar": "عين الطويلة"},
        {"id": 1323, "n": "M'toussa", "ar": "متوسة"},
        {"id": 1311, "n": "Bouhmama", "ar": "بوحمامة"},
        {"id": 1317, "n": "El Oueldja", "ar": "الولجة"},
        {"id": 1322, "n": "M'sara", "ar": "مصارة"},
        {"id": 1312, "n": "Chechar", "ar": "ششار"}
      ]
    },
    "41": {
      "id": "41",
      "n": "Souk Ahras",
      "ar": "سوق أهراس",
      "c": [
        {"id": 1349, "n": "Souk Ahras", "ar": "سوق أهراس"},
        {"id": 1329, "n": "Ain Soltane", "ar": "عين سلطان"},
        {"id": 1347, "n": "Sedrata", "ar": "سدراتة"},
        {"id": 1334, "n": "Hanencha", "ar": "الحنانشة"},
        {"id": 1337, "n": "Machroha", "ar": "المشروحة"},
        {"id": 1330, "n": "Ain Zana", "ar": "عين الزانة"},
        {"id": 1341, "n": "Ouled Driss", "ar": "أولاد إدريس"},
        {"id": 1351, "n": "Terraguelt", "ar": "ترقالت"},
        {"id": 1343, "n": "Oum El Adhaim", "ar": "أم العظايم"},
        {"id": 1340, "n": "Oued Kebrit", "ar": "وادي الكبريت"},
        {"id": 1352, "n": "Tiffech", "ar": "تيفاش"},
        {"id": 1345, "n": "Ragouba", "ar": "الراقوبة"},
        {"id": 1332, "n": "Drea", "ar": "الدريعة"},
        {"id": 1350, "n": "Taoura", "ar": "تاورة"},
        {"id": 1353, "n": "Zaarouria", "ar": "الزعرورية"},
        {"id": 1333, "n": "Haddada", "ar": "الحدادة"},
        {"id": 1335, "n": "Khedara", "ar": "الخضارة"},
        {"id": 1342, "n": "Ouled Moumen", "ar": "أولاد مومن"},
        {"id": 1339, "n": "Merahna", "ar": "المراهنة"},
        {"id": 1344, "n": "Ouillen", "ar": "ويلان"},
        {"id": 1348, "n": "Sidi Fredj", "ar": "سيدي فرج"},
        {"id": 1331, "n": "Bir Bouhouche", "ar": "بئر بوحوش"},
        {"id": 1346, "n": "Safel El Ouiden", "ar": "سافل الويدان"},
        {"id": 1336, "n": "Khemissa", "ar": "خميسة"},
        {"id": 1338, "n": "M'daourouche", "ar": "مداوروش"},
        {"id": 1354, "n": "Zouabi", "ar": "الزوابي"}
      ]
    },
    "42": {
      "id": "42",
      "n": "Tipaza",
      "ar": "تيبازة",
      "c": [
        {"id": 1369, "n": "Hadjout", "ar": "حجوط"},
        {"id": 1375, "n": "Merad", "ar": "مراد"},
        {"id": 1374, "n": "Menaceur", "ar": "مناصر"},
        {"id": 1355, "n": "Aghbal", "ar": "أغبال"},
        {"id": 1377, "n": "Nador", "ar": "الناظور"},
        {"id": 1381, "n": "Sidi-Amar", "ar": "سيدي عامر"},
        {"id": 1368, "n": "Gouraya", "ar": "قوراية"},
        {"id": 1376, "n": "Messelmoun", "ar": "مسلمون"},
        {"id": 1364, "n": "Cherchell", "ar": "شرشال"},
        {"id": 1370, "n": "Hadjret Ennous", "ar": "حجرة النص"},
        {"id": 1378, "n": "Sidi Ghiles", "ar": "سيدي غيلاس"},
        {"id": 1365, "n": "Damous", "ar": "الداموس"},
        {"id": 1373, "n": "Larhat", "ar": "الأرهاط"},
        {"id": 1367, "n": "Fouka", "ar": "فوكة"},
        {"id": 1357, "n": "Ain Tagourait", "ar": "عين تاقورايت"},
        {"id": 1360, "n": "Bou Haroun", "ar": "بوهارون"},
        {"id": 1361, "n": "Bou Ismail", "ar": "بواسماعيل"},
        {"id": 1371, "n": "Khemisti", "ar": "خميستي"},
        {"id": 1356, "n": "Ahmer El Ain", "ar": "أحمر العين"},
        {"id": 1362, "n": "Bourkika", "ar": "بورقيقة"},
        {"id": 1366, "n": "Douaouda", "ar": "دواودة"},
        {"id": 1379, "n": "Sidi Rached", "ar": "سيدي راشد"},
        {"id": 1358, "n": "Attatba", "ar": "الحطاطبة"},
        {"id": 1363, "n": "Chaiba", "ar": "الشعيبة"},
        {"id": 1372, "n": "Kolea", "ar": "القليعة"},
        {"id": 1380, "n": "Sidi Semiane", "ar": "سيدي سميان"},
        {"id": 1382, "n": "Tipaza", "ar": "تيبازة"},
        {"id": 1359, "n": "Beni Mileuk", "ar": "بني ميلك"}
      ]
    },
    "43": {
      "id": "43",
      "n": "Mila",
      "ar": "ميلة",
      "c": [
        {"id": 1394, "n": "El Mechira", "ar": "مشيرة"},
        {"id": 1393, "n": "El Ayadi Barbes", "ar": "العياضي برباس"},
        {"id": 1384, "n": "Ain Beida Harriche", "ar": " عين البيضاء أحريش"},
        {"id": 1411, "n": "Tassala Lematai", "ar": "تسالة لمطاعي"},
        {"id": 1410, "n": "Terrai Bainen", "ar": "ترعي باينان"},
        {"id": 1387, "n": "Amira Arres", "ar": "اعميرة اراس"},
        {"id": 1408, "n": "Tassadane Haddada", "ar": "تسدان حدادة"},
        {"id": 1399, "n": "Minar Zarza", "ar": "مينار زارزة"},
        {"id": 1406, "n": "Sidi Merouane", "ar": "سيدي مروان"},
        {"id": 1391, "n": "Chigara", "ar": "الشيقارة"},
        {"id": 1397, "n": "Hamala", "ar": "حمالة"},
        {"id": 1396, "n": "Grarem Gouga", "ar": "القرارم قوقة"},
        {"id": 1412, "n": "Tiberguent", "ar": "تيبرقنت"},
        {"id": 1404, "n": "Rouached", "ar": "الرواشد"},
        {"id": 1392, "n": "Derrahi Bousselah", "ar": "دراحي بوصلاح"},
        {"id": 1414, "n": "Zeghaia", "ar": "زغاية"},
        {"id": 1401, "n": "Oued Endja", "ar": "وادي النجاء"},
        {"id": 1383, "n": "Ahmed Rachedi", "ar": "أحمد راشدي"},
        {"id": 1407, "n": "Tadjenanet", "ar": "تاجنانت"},
        {"id": 1385, "n": "Ain Mellouk", "ar": "عين الملوك"},
        {"id": 1403, "n": "Ouled Khalouf", "ar": "أولاد اخلوف"},
        {"id": 1388, "n": "Benyahia Abderrahmane", "ar": "بن يحي عبد الرحمن"},
        {"id": 1409, "n": "Teleghma", "ar": "التلاغمة"},
        {"id": 1402, "n": "Oued Seguen", "ar": "وادي سقان"},
        {"id": 1400, "n": "Oued Athmenia", "ar": "وادي العثمانية"},
        {"id": 1386, "n": "Ain Tine", "ar": "عين التين"},
        {"id": 1390, "n": "Chelghoum Laid", "ar": "شلغوم العيد"},
        {"id": 1413, "n": "Yahia Beniguecha", "ar": "يحي بني قشة"},
        {"id": 1395, "n": "Ferdjioua", "ar": "فرجيوة"},
        {"id": 1405, "n": "Sidi Khelifa", "ar": "سيدي خليفة"},
        {"id": 1398, "n": "Mila", "ar": "ميلة"},
        {"id": 1389, "n": "Bouhatem", "ar": "بوحاتم"}
      ]
    },
    "44": {
      "id": "44",
      "n": "Aïn Defla",
      "ar": "عين الدفلة",
      "c": [
        {"id": 1440, "n": "Khemis-Miliana", "ar": "خميس مليانة"},
        {"id": 1446, "n": "Sidi-Lakhdar", "ar": "سيدي الأخضر"},
        {"id": 1415, "n": "Ain-Benian", "ar": "عين البنيان"},
        {"id": 1420, "n": "Ain-Torki", "ar": "عين التركي"},
        {"id": 1437, "n": "Hammam-Righa", "ar": "حمام ريغة"},
        {"id": 1429, "n": "Bourached", "ar": "بوراشد"},
        {"id": 1439, "n": "Hoceinia", "ar": "الحسينية"},
        {"id": 1430, "n": "Djelida", "ar": "جليدة"},
        {"id": 1421, "n": "Arib", "ar": "عريب"},
        {"id": 1431, "n": "Djemaa Ouled Cheikh", "ar": "جمعة أولاد الشيخ"},
        {"id": 1434, "n": "El-Amra", "ar": "العامرة"},
        {"id": 1435, "n": "El-Attaf", "ar": "العطاف"},
        {"id": 1449, "n": "Tiberkanine", "ar": "تبركانين"},
        {"id": 1416, "n": "Ain-Bouyahia", "ar": "عين بويحيى"},
        {"id": 1433, "n": "El-Abadia", "ar": "العبادية"},
        {"id": 1447, "n": "Tacheta Zegagha", "ar": "تاشتة زقاغة"},
        {"id": 1422, "n": "Birbouche", "ar": "بربوش"},
        {"id": 1432, "n": "Djendel", "ar": "جندل"},
        {"id": 1425, "n": "Ben Allal", "ar": "بن علال"},
        {"id": 1443, "n": "Oued Chorfa", "ar": "وادي الشرفاء"},
        {"id": 1428, "n": "Boumedfaa", "ar": "بومدفع"},
        {"id": 1418, "n": "Ain-Lechiakh", "ar": "عين الاشياخ"},
        {"id": 1419, "n": "Ain-Soltane", "ar": "عين السلطان"},
        {"id": 1444, "n": "Oued Djemaa", "ar": "واد الجمعة"},
        {"id": 1436, "n": "El-Maine", "ar": "الماين"},
        {"id": 1445, "n": "Rouina", "ar": "الروينة"},
        {"id": 1450, "n": "Zeddine", "ar": "زدين"},
        {"id": 1426, "n": "Bir-Ould-Khelifa", "ar": "بئر ولد خليفة"},
        {"id": 1427, "n": "Bordj-Emir-Khaled", "ar": "برج الأمير خالد"},
        {"id": 1448, "n": "Tarik-Ibn-Ziad", "ar": "طارق بن زياد"},
        {"id": 1423, "n": "Bathia", "ar": "بطحية"},
        {"id": 1424, "n": "Belaas", "ar": "بلعاص"},
        {"id": 1438, "n": "Hassania", "ar": "الحسانية"},
        {"id": 1417, "n": "Ain-Defla", "ar": "عين الدفلى"},
        {"id": 1442, "n": "Miliana", "ar": "مليانة"},
        {"id": 1441, "n": "Mekhatria", "ar": "المخاطرية"}
      ]
    },
    "45": {
      "id": "45",
      "n": "Naâma",
      "ar": "النعامة",
      "c": [
        {"id": 1462, "n": "Tiout", "ar": "تيوت"},
        {"id": 1459, "n": "Moghrar", "ar": "مغرار"},
        {"id": 1453, "n": "Asla", "ar": "عسلة"},
        {"id": 1456, "n": "Kasdir", "ar": "القصدير"},
        {"id": 1457, "n": "Makmen Ben Amar", "ar": "مكمن بن عمار"},
        {"id": 1452, "n": "Ain Sefra", "ar": "عين الصفراء"},
        {"id": 1458, "n": "Mecheria", "ar": "المشرية"},
        {"id": 1455, "n": "El Biodh", "ar": "البيوض"},
        {"id": 1451, "n": "Ain Ben Khelil", "ar": "عين بن خليل"},
        {"id": 1460, "n": "Naama", "ar": "النعامة"},
        {"id": 1454, "n": "Djenienne Bourezg", "ar": "جنين بورزق"},
        {"id": 1461, "n": "Sfissifa", "ar": "سفيسيفة"}
      ]
    },
    "46": {
      "id": "46",
      "n": "Aïn Témouchent",
      "ar": "عين تيموشنت",
      "c": [
        {"id": 1486, "n": "Sidi Boumediene", "ar": "سيدي بومدين"},
        {"id": 1489, "n": "Tamzoura", "ar": "تامزورة"},
        {"id": 1471, "n": "Chaabat El Ham", "ar": "شعبة اللحم"},
        {"id": 1474, "n": "El Maleh", "ar": "المالح"},
        {"id": 1483, "n": "Ouled Kihal", "ar": "أولاد الكيحل"},
        {"id": 1472, "n": "Chentouf", "ar": "شنتوف"},
        {"id": 1490, "n": "Terga", "ar": "تارقة"},
        {"id": 1481, "n": "Oued Sebbah", "ar": "وادي الصباح"},
        {"id": 1473, "n": "El Amria", "ar": "العامرية"},
        {"id": 1479, "n": "Hassi El Ghella", "ar": "حاسي الغلة"},
        {"id": 1482, "n": "Ouled Boudjemaa", "ar": "أولاد بوجمعة"},
        {"id": 1463, "n": "Aghlal", "ar": "أغلال"},
        {"id": 1465, "n": "Ain Kihal", "ar": "عين الكيحل"},
        {"id": 1467, "n": "Ain Tolba", "ar": "عين الطلبة"},
        {"id": 1468, "n": "Aoubellil", "ar": "عقب الليل"},
        {"id": 1469, "n": "Beni Saf", "ar": "بني صاف"},
        {"id": 1478, "n": "Hassasna", "ar": "الحساسنة"},
        {"id": 1476, "n": "Emir Abdelkader", "ar": "الأمير عبد القادر"},
        {"id": 1488, "n": "Sidi Safi", "ar": "سيدي صافي"},
        {"id": 1484, "n": "Oulhaca El Gheraba", "ar": "ولهاصة الغرابة"},
        {"id": 1487, "n": "Sidi Ouriache", "ar": "سيدي ورياش"},
        {"id": 1464, "n": "Ain El Arbaa", "ar": "عين الأربعاء"},
        {"id": 1475, "n": "El Messaid", "ar": "المساعيد"},
        {"id": 1480, "n": "Oued Berkeche", "ar": "وادي برقش"},
        {"id": 1485, "n": "Sidi Ben Adda", "ar": "سيدي بن عدة"},
        {"id": 1466, "n": "Ain Temouchent", "ar": "عين تموشنت"},
        {"id": 1470, "n": "Bouzedjar", "ar": "بوزجار"},
        {"id": 1477, "n": "Hammam Bou Hadjar", "ar": "حمام بوحجر"}
      ]
    },
    "47": {
      "id": "47",
      "n": "Ghardaïa",
      "ar": "غرداية",
      "c": [
        {"id": 1493, "n": "Dhayet Bendhahoua", "ar": "ضاية بن ضحوة"},
        {"id": 1500, "n": "Mansoura", "ar": "المنصورة"},
        {"id": 1494, "n": "El Atteuf", "ar": "العطف"},
        {"id": 1492, "n": "Bounoura", "ar": "بونورة"},
        {"id": 1503, "n": "Zelfana", "ar": "زلفانة"},
        {"id": 1497, "n": "El Guerrara", "ar": "القرارة"},
        {"id": 1502, "n": "Sebseb", "ar": "سبسب"},
        {"id": 1501, "n": "Metlili", "ar": "متليلي"},
        {"id": 1491, "n": "Berriane", "ar": "بريان"},
        {"id": 1496, "n": "Ghardaia", "ar": "غرداية"}
      ]
    },
    "48": {
      "id": "48",
      "n": "Relizane",
      "ar": "غليزان",
      "c": [
        {"id": 1516, "n": "El-Guettar", "ar": "القطار"},
        {"id": 1530, "n": "Ouled Aiche", "ar": "أولاد يعيش"},
        {"id": 1509, "n": "Beni Dergoun", "ar": "بني درقن"},
        {"id": 1511, "n": "Dar Ben Abdelah", "ar": "دار بن عبد الله"},
        {"id": 1541, "n": "Zemmoura", "ar": "زمورة"},
        {"id": 1512, "n": "Djidiouia", "ar": "جديوية"},
        {"id": 1519, "n": "Hamri", "ar": "حمري"},
        {"id": 1507, "n": "Belaassel Bouzagza", "ar": "بلعسل بوزقزة"},
        {"id": 1517, "n": "El-Matmar", "ar": "المطمر"},
        {"id": 1534, "n": "Sidi Khettab", "ar": "سيدي  خطاب"},
        {"id": 1537, "n": "Sidi M'hamed Benaouda", "ar": "سيدي امحمد بن عودة"},
        {"id": 1505, "n": "Ain-Tarek", "ar": "عين طارق"},
        {"id": 1518, "n": "Had Echkalla", "ar": "حد الشكالة"},
        {"id": 1515, "n": "El Ouldja", "ar": "الولجة"},
        {"id": 1522, "n": "Mazouna", "ar": "مازونة"},
        {"id": 1504, "n": "Ain Rahma", "ar": "عين الرحمة"},
        {"id": 1520, "n": "Kalaa", "ar": "القلعة"},
        {"id": 1538, "n": "Sidi Saada", "ar": "سيدي سعادة"},
        {"id": 1540, "n": "Yellel", "ar": "يلل"},
        {"id": 1539, "n": "Souk El Had", "ar": "سوق الحد"},
        {"id": 1524, "n": "Mendes", "ar": "منداس"},
        {"id": 1528, "n": "Oued Essalem", "ar": "وادي السلام"},
        {"id": 1535, "n": "Sidi Lazreg", "ar": "سيدي لزرق"},
        {"id": 1506, "n": "Ammi Moussa", "ar": "عمي موسى"},
        {"id": 1526, "n": "Ouarizane", "ar": "واريزان"},
        {"id": 1525, "n": "Merdja Sidi Abed", "ar": "مرجة سيدي عابد"},
        {"id": 1531, "n": "Ouled Sidi Mihoub", "ar": "أولاد سيدي الميهوب"},
        {"id": 1508, "n": "Bendaoud", "ar": "بن داود"},
        {"id": 1529, "n": "Oued-Rhiou", "ar": "وادي رهيو"},
        {"id": 1513, "n": "El Hassi", "ar": "الحاسي"},
        {"id": 1536, "n": "Sidi M'hamed Benali", "ar": "سيدي أمحمد بن علي"},
        {"id": 1523, "n": "Mediouna", "ar": "مديونة"},
        {"id": 1510, "n": "Beni Zentis", "ar": "بني زنطيس"},
        {"id": 1527, "n": "Oued El Djemaa", "ar": "وادي الجمعة"},
        {"id": 1521, "n": "Lahlef", "ar": "لحلاف"},
        {"id": 1533, "n": "Relizane", "ar": "غليزان"},
        {"id": 1514, "n": "El H'madna", "ar": "الحمادنة"},
        {"id": 1532, "n": "Ramka", "ar": "الرمكة"}
      ]
    },
    "49": {
      "id": "49",
      "n": "Timimoun",
      "ar": "تيميمون",
      "c": [
        {"id": 25, "n": "Tinerkouk", "ar": "تنركوك"},
        {"id": 24, "n": "Timimoun", "ar": "تيميمون"},
        {"id": 15, "n": "Ouled Said", "ar": "أولاد السعيد"},
        {"id": 12, "n": "Metarfa", "ar": "المطارفة"},
        {"id": 19, "n": "Talmine", "ar": "طالمين"},
        {"id": 14, "n": "Ouled Aissa", "ar": "أولاد عيسى"},
        {"id": 7, "n": "Charouine", "ar": "شروين"},
        {"id": 3, "n": "Aougrout", "ar": "أوقروت"},
        {"id": 8, "n": "Deldoul", "ar": "دلدول"},
        {"id": 11, "n": "Ksar Kaddour", "ar": "قصر قدور"}
      ]
    },
    "50": {
      "id": "50",
      "n": "Bordj Badji Mokhtar",
      "ar": "برج باجي مختار",
      "c": [
        {"id": 23, "n": "Timiaouine", "ar": "تيمياوين"},
        {"id": 5, "n": "Bordj Badji Mokhtar", "ar": "برج باجي مختار"}
      ]
    },
    "51": {
      "id": "51",
      "n": "Ouled Djellal",
      "ar": "أولاد جلال",
      "c": [
        {"id": 258, "n": "Ras El Miad", "ar": "رأس الميعاد"},
        {"id": 232, "n": "Besbes", "ar": "بسباس"},
        {"id": 259, "n": "Sidi Khaled", "ar": "سيدي  خالد"},
        {"id": 240, "n": "Doucen", "ar": "الدوسن"},
        {"id": 237, "n": "Chaiba", "ar": "الشعيبة"},
        {"id": 255, "n": "Ouled Djellal", "ar": "أولاد جلال"}
      ]
    },
    "52": {
      "id": "52",
      "n": "Béni Abbès",
      "ar": "بني عباس",
      "c": [
        {"id": 265, "n": "Beni-Abbes", "ar": "بني عباس"},
        {"id": 282, "n": "Tamtert", "ar": "تامترت"},
        {"id": 271, "n": "Igli", "ar": "إقلي"},
        {"id": 269, "n": "El Ouata", "ar": "الواتة"},
        {"id": 279, "n": "Ouled-Khodeir", "ar": "أولاد خضير"},
        {"id": 273, "n": "Kerzaz", "ar": "كرزاز"},
        {"id": 283, "n": "Timoudi", "ar": "تيمودي"},
        {"id": 274, "n": "Ksabi", "ar": "القصابي"},
        {"id": 266, "n": "Beni-Ikhlef", "ar": "بن يخلف"}
      ]
    },
    "53": {
      "id": "53",
      "n": "In Salah",
      "ar": "عين صالح",
      "c": [
        {"id": 360, "n": "Inghar", "ar": "إينغر"},
        {"id": 357, "n": "Ain Salah", "ar": "عين صالح"},
        {"id": 358, "n": "Foggaret Ezzoua", "ar": "فقارة الزوى"}
      ]
    },
    "54": {
      "id": "54",
      "n": "In Guezzam",
      "ar": "عين قزام",
      "c": [
        {"id": 363, "n": "Tin Zouatine", "ar": "تين زواتين"},
        {"id": 356, "n": "Ain Guezzam", "ar": "عين قزام"}
      ]
    },
    "55": {
      "id": "55",
      "n": "Touggourt",
      "ar": "تقرت",
      "c": [
        {"id": 1107, "n": "Temacine", "ar": "تماسين"},
        {"id": 1104, "n": "Sidi Slimane", "ar": "سيدي سليمان"},
        {"id": 1097, "n": "Megarine", "ar": "المقارين"},
        {"id": 1099, "n": "Nezla", "ar": "النزلة"},
        {"id": 1091, "n": "Blidet Amor", "ar": "بلدة اعمر"},
        {"id": 1106, "n": "Tebesbest", "ar": "تبسبست"},
        {"id": 1108, "n": "Touggourt", "ar": "تقرت"},
        {"id": 1105, "n": "Taibet", "ar": "الطيبات"},
        {"id": 1092, "n": "El Alia", "ar": "العالية"},
        {"id": 1094, "n": "El-Hadjira", "ar": "الحجيرة"},
        {"id": 1090, "n": "Benaceur", "ar": "بن ناصر"},
        {"id": 1098, "n": "M'naguer", "ar": "المنقر"},
        {"id": 1109, "n": "Zaouia El Abidia", "ar": "الزاوية العابدية"}
      ]
    },
    "56": {
      "id": "56",
      "n": "Djanet",
      "ar": "جانت",
      "c": [
        {"id": 1161, "n": "Djanet", "ar": "جانت"},
        {"id": 1158, "n": "Bordj El Haouass", "ar": "برج الحواس"}
      ]
    },
    "57": {
      "id": "57",
      "n": "El Meghaier",
      "ar": "المغير",
      "c": [
        {"id": 1296, "n": "Oum Touyour", "ar": "أم الطيور"},
        {"id": 1300, "n": "Sidi Amrane", "ar": "سيدي عمران"},
        {"id": 1293, "n": "M'rara", "ar": "المرارة"},
        {"id": 1281, "n": "Djamaa", "ar": "جامعة"},
        {"id": 1306, "n": "Tenedla", "ar": "تندلة"},
        {"id": 1284, "n": "El-M'ghaier", "ar": "المغير"},
        {"id": 1303, "n": "Still", "ar": "سطيل"},
        {"id": 1302, "n": "Sidi Khelil", "ar": "سيدي خليل"}
      ]
    },
    "58": {
      "id": "58",
      "n": "El Menia",
      "ar": "المنيعة",
      "c": [
        {"id": 1495, "n": "El Meniaa", "ar": "المنيعة"},
        {"id": 1499, "n": "Hassi Gara", "ar": "حاسي القارة"},
        {"id": 1498, "n": "Hassi Fehal", "ar": "حاسي الفحل"}
      ]
    }
  };
}
