package oracle

const (
	Insert_Insured = "INSERT INTO INSURED (NAME) VALUES (:1)"
	Login_SQL      = "SELECT ID FROM USERT WHERE USERNAME = :USERNAME and PASSWORD= :PASSWORD"
	GET_ROLE_SQL   = "SELECT ROLE_ID FROM USERT WHERE ID = :ID"
)
